import { Subject } from "../../types/subject";

export interface TopicDefinition {
  id: string;
  name: string;
}

export interface SubjectWithTopics extends Subject {
  topics: TopicDefinition[];
}

export const YKS_SUBJECTS: SubjectWithTopics[] = [
  // TYT Subjects
  {
    id: "tyt_turkce",
    name: "TYT Türkçe",
    category: "TYT",
    questionCount: 40,
    topics: [
      { id: "t_sozcukte_anlam", name: "Sözcükte Anlam" },
      { id: "t_cumlede_anlam", name: "Cümlede Anlam" },
      { id: "t_paragraf", name: "Paragrafta Anlam ve Yapı" },
      { id: "t_ses_bilgisi", name: "Ses Bilgisi" },
      { id: "t_yazim_kurallari", name: "Yazım Kuralları" },
      { id: "t_noktalama", name: "Noktalama İşaretleri" },
      { id: "t_sozcuk_turleri", name: "Sözcük Türleri (İsim, Sıfat, Zamir, Zarf, Edat, Bağlaç)" },
      { id: "t_fiiller", name: "Fiiller ve Fiilimsiler" },
      { id: "t_cumle_bilgisi", name: "Cümlenin Ögeleri ve Cümle Türleri" },
      { id: "t_anlam_bozuklugu", name: "Anlatım Bozuklukları" },
    ],
  },
  {
    id: "tyt_matematik",
    name: "TYT Matematik",
    category: "TYT",
    questionCount: 40,
    topics: [
      { id: "tm_temel_kavramlar", name: "Temel Kavramlar ve Sayı Kümeleri" },
      { id: "tm_bolme_bolunebilme", name: "Bölme ve Bölünebilme Kuralları" },
      { id: "tm_ebob_ekok", name: "EBOB - EKOK" },
      { id: "tm_rasyonel_sayilar", name: "Rasyonel ve Ondalık Sayılar" },
      { id: "tm_uslu_koklu", name: "Üslü ve Köklü İfadeler" },
      { id: "tm_mutlak_deger", name: "Mutlak Değer" },
      { id: "tm_carpanlara_ayirma", name: "Çarpanlara Ayırma" },
      { id: "tm_oran_oranti", name: "Oran - Orantı" },
      { id: "tm_problemler", name: "Problemler (Sayı, Kesir, Yaş, Yüzde, Kar-Zarar, Hız, Karışım)" },
      { id: "tm_kume_mantik", name: "Kümeler ve Mantık" },
      { id: "tm_fonksiyonlar", name: "Fonksiyonlar" },
      { id: "tm_pkob", name: "Permütasyon, Kombinasyon, Olasılık" },
      { id: "tm_geometri_ucgenler", name: "Geometri: Üçgenler ve Doğruda Açı" },
      { id: "tm_geometri_dortgenler", name: "Geometri: Dörtgenler ve Çokgenler" },
      { id: "tm_geometri_cember", name: "Geometri: Çember ve Daire" },
      { id: "tm_geometri_kati_cisim", name: "Geometri: Katı Cisimler" },
    ],
  },
  {
    id: "tyt_sosyal",
    name: "TYT Sosyal Bilimler",
    category: "TYT",
    questionCount: 20,
    topics: [
      { id: "ts_tarih_ilk_cag", name: "Tarih: Tarih ve Zaman & İlk Çağ Uygarlıkları" },
      { id: "ts_tarih_islam", name: "Tarih: Türk-İslam Tarihi & Osmanlı Devleti" },
      { id: "ts_tarih_inkilap", name: "Tarih: Milli Mücadele ve Atatürk İnkılapları" },
      { id: "ts_cog_harita", name: "Coğrafya: Harita Bilgisi ve Dünyanın Şekli" },
      { id: "ts_cog_iklim", name: "Coğrafya: İklim Bilgisi ve Türkiye'nin İklimi" },
      { id: "ts_cog_nufus", name: "Coğrafya: Nüfus, Yerleşme ve Afetler" },
      { id: "ts_fel_felsefe", name: "Felsefe: Felsefenin Konusu ve Bilgi Felsefesi" },
      { id: "ts_fel_ahlak_din", name: "Felsefe & Din: Ahlak, Sanat ve Din Kültürü İbadet/Ahlak" },
    ],
  },
  {
    id: "tyt_fen",
    name: "TYT Fen Bilimleri",
    category: "TYT",
    questionCount: 20,
    topics: [
      { id: "tf_fizik_madde", name: "Fizik: Fizik Bilimine Giriş & Madde ve Özellikleri" },
      { id: "tf_fizik_hareket", name: "Fizik: Hareket, Kuvvet ve İş-Güç-Enerji" },
      { id: "tf_fizik_isi_optik", name: "Fizik: Isı-Sıcaklık, Elektrik ve Optik" },
      { id: "tf_kimya_kimyasal", name: "Kimya: Kimya Bilimi ve Atomun Yapısı" },
      { id: "tf_kimya_periyodik", name: "Kimya: Periyodik Sistem ve Kimyasal Türler Arası Etkileşim" },
      { id: "tf_kimya_asit_baz", name: "Kimya: Maddenin Halleri, Mol ve Asit-Baz-Tuz" },
      { id: "tf_biyo_hucre", name: "Biyoloji: Canlıların Ortak Özellikleri ve Hücre" },
      { id: "tf_biyo_canlilar", name: "Biyoloji: Canlılar Dünyası ve Kalıtım" },
      { id: "tf_biyo_ekoloji", name: "Biyoloji: Ekosistem Ekolojisi" },
    ],
  },

  // AYT Subjects
  {
    id: "ayt_matematik",
    name: "AYT Matematik",
    category: "AYT",
    allowedTracks: ["Sayısal", "Eşit Ağırlık"],
    questionCount: 40,
    topics: [
      { id: "am_polinomlar", name: "Polinomlar ve II. Dereceden Denklemler" },
      { id: "am_parabol_esitsizlik", name: "Parabol ve Eşitsizlikler" },
      { id: "am_logaritma", name: "Logaritma" },
      { id: "am_diziler", name: "Diziler (Aritmetik ve Geometrik Dizi)" },
      { id: "am_trigonometri", name: "Trigonometri" },
      { id: "am_limit", name: "Limit ve Süreklilik" },
      { id: "am_turev", name: "Türev ve Uygulamaları" },
      { id: "am_integral", name: "İntegral ve Alan Hesabı" },
      { id: "am_analitik_geo", name: "Analitik Geometri ve Dönüşümler" },
      { id: "am_cember_analitik", name: "Çemberin Analitik İncelenmesi" },
    ],
  },
  {
    id: "ayt_fizik",
    name: "AYT Fizik",
    category: "AYT",
    allowedTracks: ["Sayısal"],
    questionCount: 14,
    topics: [
      { id: "af_vektor_tork", name: "Vektörler, Tork ve Denge" },
      { id: "af_atislar_momentum", name: "Atışlar, İtme ve Çizgisel Momentum" },
      { id: "af_elektrik_manyetizma", name: "Elektriksel Kuvvet, Potansiyel ve Manyetizma" },
      { id: "af_alternatif_akım", name: "Alternatif Akım ve Transformatörler" },
      { id: "af_cembersel_hareket", name: "Düzgün Çembersel Hareket ve Basit Harmonik Hareket" },
      { id: "af_dalga_organ", name: "Dalga Mekaniği ve Elektromanyetik Dalgalar" },
      { id: "af_modern_fizik", name: "Atom Fizigine Giriş ve Modern Fizik" },
    ],
  },
  {
    id: "ayt_kimya",
    name: "AYT Kimya",
    category: "AYT",
    allowedTracks: ["Sayısal"],
    questionCount: 13,
    topics: [
      { id: "ak_modern_atom", name: "Modern Atom Teorisi ve Periyodik Cetvel" },
      { id: "ak_gazlar", name: "Gazlar" },
      { id: "ak_sivi_cozeltiler", name: "Sıvı Çözeltiler ve Koligatif Özellikler" },
      { id: "ak_kimyasal_tepkime", name: "Tepkimelerde Enerji ve Tepkime Hızı" },
      { id: "ak_denge", name: "Kimyasal Denge ve Asit-Baz Dengesi" },
      { id: "ak_elektrokimya", name: "Kimya ve Elektrik (Elektrokimya)" },
      { id: "ak_organik", name: "Organik Kimyaya Giriş ve Organik Bileşikler" },
    ],
  },
  {
    id: "ayt_biyoloji",
    name: "AYT Biyoloji",
    category: "AYT",
    allowedTracks: ["Sayısal"],
    questionCount: 13,
    topics: [
      { id: "ab_sistemler", name: "Insan Fizyolojisi ve Sistemler (Sinir, Destek, Sindirim, Dolaşım)" },
      { id: "ab_solunum_bosaltim", name: "Solunum Sistemi, Boşaltım Sistemi ve Üreme" },
      { id: "ab_komunite", name: "Komünite ve Popülasyon Ekolojisi" },
      { id: "ab_genco", name: "Genden Proteine (Nükleik Asitler ve Protein Sentezi)" },
      { id: "ab_fotosentez_solunum", name: "Canlılarda Enerji Dönüşümleri (Fotosentez, Kemosentez, Hücresel Solunum)" },
      { id: "ab_bitki", name: "Bitki Biyolojisi" },
    ],
  },
  {
    id: "ayt_edebiyat",
    name: "AYT Türk Dili ve Edebiyatı",
    category: "AYT",
    allowedTracks: ["Eşit Ağırlık", "Sözel"],
    questionCount: 24,
    topics: [
      { id: "ae_siir_bilgisi", name: "Şiir Bilgisi ve Edebi Sanatlar" },
      { id: "ae_islamiyet_oncesi", name: "İslamiyet Öncesi ve Geçiş Dönemi Türk Edebiyatı" },
      { id: "ae_halk_edebiyati", name: "Halk Edebiyatı" },
      { id: "ae_divan_edebiyati", name: "Divan Edebiyatı" },
      { id: "ae_tanzimat_servet", name: "Tanzimat, Servet-i Fünun ve Fecr-i Ati Edebiyatı" },
      { id: "ae_milli_edebiyat", name: "Milli Edebiyat Dönemi" },
      { id: "ae_cumhuriyet", name: "Cumhuriyet Dönemi Türk Edebiyatı" },
      { id: "ae_edebi_akimlar", name: "Edebi Akımlar" },
    ],
  },
  {
    id: "ayt_tarih1",
    name: "AYT Tarih-1",
    category: "AYT",
    allowedTracks: ["Eşit Ağırlık", "Sözel"],
    questionCount: 10,
    topics: [
      { id: "at1_tarih_zaman", name: "Tarih Bilimi ve İlk Çağ Medeniyetleri" },
      { id: "at1_orta_cag", name: "Orta Çağda Dünya ve Türk Dünyası" },
      { id: "at1_osmanli_kurulus", name: "Osmanlı Devleti Kuruluş ve Yükselme Dönemi" },
      { id: "at1_20yy_osmanli", name: "20. Yüzyıl Başlarında Osmanlı Devleti ve I. Dünya Savaşı" },
      { id: "at1_inkilap", name: "Milli Mücadele Dönemi ve Atatürkçülük" },
    ],
  },
  {
    id: "ayt_cografya1",
    name: "AYT Coğrafya-1",
    category: "AYT",
    allowedTracks: ["Eşit Ağırlık", "Sözel"],
    questionCount: 6,
    topics: [
      { id: "ac1_ekosistem", name: "Ekosistem ve Biyoçeşitlilik" },
      { id: "ac1_sehirler", name: "Şehirlerin Fonksiyonları ve Kırsal Yerleşmeler" },
      { id: "ac1_turkiye_ekonomi", name: "Türkiye'nin Ekonomi Politikaları ve Sanayi" },
      { id: "ac1_kuresellesen_dunya", name: "Küreselleşen Dünya ve Uluslararası Örgütler" },
    ],
  },
];
