import type { ManifestQuote } from "./types";

export const QUOTES1: ManifestQuote[] = [
  { id: "mq_001", text: "Bir şeyin işe yaramadığı 10.000 yol bulursam başarısız olmuş sayılmam. Cesaretim kırılmaz; çünkü elenen her yanlış deneme ileriye atılmış bir adımdır.", author: "Thomas Edison" },
  { id: "mq_002", text: "Sen kendine inanmadıkça kimse sana inanmaz.", author: "Liberace" },
  { id: "mq_003", text: "Şimdi harekete geç. Gelecek hiç kimseye vaat edilmiş değildir.", author: "Wayne Dyer" },
  { id: "mq_004", text: "Yaratıcı insanı motive eden şey başkalarını yenmek değil, başarmak arzusudur.", author: "Ayn Rand" },
  { id: "mq_005", text: "Asla vazgeçme; çünkü gidişatın değişeceği yer ve zaman tam da o an olabilir.", author: "Harriet Beecher Stowe" },
  { id: "mq_006", text: "Herkesten daha iyi olman gerektiğine inanmıyorum. Olabileceğini düşündüğünden daha iyi olman gerektiğine inanıyorum.", author: "Ken Venturi" },
  { id: "mq_007", text: "Bekleme. Zaman hiçbir zaman tam anlamıyla uygun olmayacak.", author: "Napoleon Hill" },
  { id: "mq_008", text: "Çaba, ödülünü ancak insan vazgeçmeyi reddettiğinde tam olarak verir.", author: "Napoleon Hill" },
  { id: "mq_009", text: "Başarmak için önce başarabileceğimize inanmalıyız.", author: "Nikos Kazantzakis" },
  { id: "mq_010", text: "Sevdiğin işi seçersen hayatında bir gün bile çalışmış gibi hissetmezsin.", author: "Confucius" },
  { id: "mq_011", text: "Her büyük hayal bir hayalperestle başlar. Dünyayı değiştirecek yıldızlara ulaşmak için gereken güç, sabır ve tutkunun içinde olduğunu daima hatırla.", author: "Harriet Tubman" },
  { id: "mq_012", text: "Başarılı olmak istiyorsan, kabul görmüş başarı yollarında yürümek yerine yeni yollar açmalısın.", author: "John Locke" },
  { id: "mq_013", text: "Kendine inan! Yeteneklerine güven! Kendi gücüne alçakgönüllü ama makul bir güven duymadan başarılı ya da mutlu olamazsın.", author: "Norman Vincent Peale" },
  { id: "mq_014", text: "Başarma kararlılığının, diğer her şeyden daha önemli olduğunu daima aklında tut.", author: "Abraham Lincoln" },
  { id: "mq_015", text: "Kışın en derininde, sonunda içimde yenilmez bir yaz olduğunu öğrendim.", author: "Albert Camus" },
  { id: "mq_016", text: "Dünden öğren, bugün için yaşa, yarın için umut et.", author: "Albert Einstein" },
  { id: "mq_017", text: "Denemeye cesaret eden için imkânsız diye bir şey yoktur.", author: "Alexander the Great" },
  { id: "mq_018", text: "Hayalim hep önümden koşuyordu. Ona yetişmek ve bir anlığına onunla aynı ritimde yaşamak mucizeydi.", author: "Anaïs Nin" },
  { id: "mq_019", text: "Büyük işler başarmak için yalnızca harekete geçmek değil, hayal kurmak; yalnızca plan yapmak değil, inanmak da gerekir.", author: "Anatole France" },
  { id: "mq_020", text: "Hedeflerini yüksek tut ve onlara ulaşana kadar durma.", author: "Bo Jackson" },
  { id: "mq_021", text: "Nasıl düşünürsen öyle olursun.", author: "Bruce Lee" },
  { id: "mq_022", text: "Değişim zamanlarında dünyayı öğrenenler devralır; yalnızca öğrenmiş olanlar ise artık var olmayan bir dünyaya kusursuzca hazırlanmış kalırlar.", author: "Eric Hoffer" },
  { id: "mq_023", text: "Çok çalışmadan yabani otlardan başka hiçbir şey büyümez.", author: "Gordon Hinckley" },
  { id: "mq_024", text: "İyimserlik başarıya götüren inançtır. Umut ve güven olmadan hiçbir şey başarılamaz.", author: "Helen Keller" },
  { id: "mq_025", text: "Yapabileceğini düşünüyorsan da yapamayacağını düşünüyorsan da haklısın.", author: "Henry Ford" },
  { id: "mq_026", text: "Kalbinin derinliklerinde büyük işler yapmak için yaratıldığına inan.", author: "Joe Paterno" },
  { id: "mq_027", text: "Hedefe yaklaştıkça zorluklar artar.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_028", text: "Zor işleri kolayken, büyük işleri küçükken yap. Binlerce kilometrelik yolculuk tek bir adımla başlar.", author: "Laozi" },
  { id: "mq_029", text: "Dünyayı değiştiriyorsan önemli şeyler üzerinde çalışıyorsun demektir. Sabah kalkmak için heyecan duyarsın.", author: "Larry Page" },
  { id: "mq_030", text: "Başarma kararlılığım yeterince güçlüyse başarısızlık beni asla alt edemez.", author: "Og Mandino" },
  { id: "mq_031", text: "Geleceği öngörmenin en iyi yolu onu yaratmaktır.", author: "Peter Drucker" },
  { id: "mq_032", text: "Hayatını bugün değiştir. Geleceği şansa bırakma; gecikmeden şimdi harekete geç.", author: "Simone de Beauvoir" },
  { id: "mq_033", text: "Ayaklarına değil yıldızlara bak. Gördüklerini anlamaya çalış, evrenin neden var olduğunu merak et. Meraklı ol.", author: "Stephen Hawking" },
  { id: "mq_034", text: "En büyük zayıflığımız vazgeçmektir. Başarının en kesin yolu her zaman bir kez daha denemektir.", author: "Thomas Edison" },
  { id: "mq_035", text: "Hedef belirlemek, görünmeyeni görünür hâle getirmenin ilk adımıdır.", author: "Tony Robbins" },
  { id: "mq_036", text: "Hayal edebiliyorsan yapabilirsin.", author: "Walt Disney" },
  { id: "mq_037", text: "Zorluklar cesaret kırmak için değil, bizi harekete geçirmek içindir. İnsan ruhu mücadeleyle güçlenir.", author: "William Ellery Channing" },
  { id: "mq_038", text: "Hedeflerine ulaşınca elde ettiğin şeyler, o hedeflere ulaşırken dönüştüğün kişi kadar önemli değildir.", author: "Zig Ziglar" },
  { id: "mq_039", text: "Başarma kararlılığının diğer her şeyden daha önemli olduğunu daima hatırla.", author: "Abraham Lincoln" },
  { id: "mq_040", text: "A hayattaki başarıysa A, x artı y artı z'dir. x çalışmak, y oyun, z ise ne zaman susacağını bilmektir.", author: "Albert Einstein" },
  { id: "mq_041", text: "Başarı mutluluğun anahtarı değildir. Mutluluk başarının anahtarıdır. Yaptığın işi seviyorsan başarılı olursun.", author: "Albert Schweitzer" },
  { id: "mq_042", text: "İlerlemenin sanatı, değişimin içinde düzeni; düzenin içinde de değişimi korumaktır.", author: "Alfred North Whitehead" },
  { id: "mq_043", text: "Tek bir hedefi durmadan takip etmek: başarının sırrı budur.", author: "Anna Pavlova" },
  { id: "mq_044", text: "Başarının kesin bir formülü yoktur; belki de hayatı ve getirdiklerini koşulsuz kabul etmek dışında.", author: "Arthur Rubinstein" },
  { id: "mq_045", text: "Hayatı yalnızca para kazanmaya odaklamak, hedeflerinin yoksulluğunu gösterir. Kendinden çok az şey ister ve sonunda seni tatminsiz bırakır.", author: "Barack Obama" },
  { id: "mq_046", text: "Hayatta başarının sırlarından biri, fırsat geldiğinde ona hazır olmaktır.", author: "Benjamin Disraeli" },
  { id: "mq_047", text: "Başarının sırrı, amaca bağlılıktır.", author: "Benjamin Disraeli" },
  { id: "mq_048", text: "Azim sayesinde birçok insan, kesin başarısızlık gibi görünen şeyden başarı çıkarır.", author: "Benjamin Disraeli" },
  { id: "mq_049", text: "Daima kendin ol, kendini ifade et, kendine güven; başarılı bir kişilik arayıp onu kopyalamaya çalışma.", author: "Bruce Lee" },
  { id: "mq_050", text: "Hayatta başarılı olan kişi, hedefini sürekli gören ve ona şaşmadan yönelen kişidir. Adanmışlık budur.", author: "Cecil B. DeMille" },
  { id: "mq_051", text: "İnsan başarıya doğru ilerlerken başarısızlıklar yaşayabilir.", author: "Charles F. Kettering" },
  { id: "mq_052", text: "Tek bir başarı vardır: hayatını kendi istediğin şekilde yaşayabilmek.", author: "Christopher Morley" },
  { id: "mq_053", text: "Tek bir başarı vardır: hayatını kendi istediğin şekilde yaşayabilmek.", author: "Christopher Morley" },
  { id: "mq_054", text: "Başarının sırrı yoktur. Başarı; hazırlığın, sıkı çalışmanın ve başarısızlıklardan öğrenmenin sonucudur.", author: "Colin Powell" },
  { id: "mq_055", text: "Hayatı dolu dolu, yaşam enerjisiyle yaşayan kişi başarılı bir hayat sürer.", author: "Daisaku Ikeda" },
  { id: "mq_056", text: "Başarılı kişi, başkalarının ona attığı tuğlalarla sağlam bir temel kurabilendir.", author: "David Brinkley" },
  { id: "mq_057", text: "Gerçek başarı, hayatının işini sevdiğin işte bulmaktır.", author: "David McCullough" },
  { id: "mq_058", text: "Bir araya gelmek başlangıçtır; birlikte kalmak ilerleme, birlikte çalışmak başarıdır.", author: "Edward Everett Hale" },
  { id: "mq_059", text: "Biraz daha ısrar, biraz daha çaba; umutsuz görünen başarısızlığı görkemli bir başarıya dönüştürebilir.", author: "Elbert Hubbard" },
  { id: "mq_060", text: "Her zor ve tehlikeli şey eğitim için uygun değildir; yalnızca çabamızın amacına ulaşmamıza yardım eden şey uygundur.", author: "Epictetus" },
  { id: "mq_061", text: "Yeni, farklı ve daha iyi bir başarıyı başarısızlıklarımızın üzerine kurarız.", author: "Havelock Ellis" },
  { id: "mq_062", text: "İnsan hayalinin yönünde güvenle ilerler ve tasarladığı hayatı yaşamaya çalışırsa, sıradan zamanlarda beklemediği bir başarıyla karşılaşır.", author: "Henry David Thoreau" },
  { id: "mq_063", text: "Azim başarının büyük bir unsurudur. Kapıyı yeterince uzun ve güçlü çalarsan sonunda mutlaka birini uyandırırsın.", author: "Henry Wadsworth Longfellow" },
  { id: "mq_064", text: "Sana başarının formülünü veremem ama başarısızlığın formülünü verebilirim: herkesi memnun etmeye çalışmak.", author: "Herbert Bayard Swope" },
  { id: "mq_065", text: "Sonuçlara odaklanırsan değişemezsin. Değişime odaklanırsan sonuç alırsın.", author: "Jack Dixon" },
  { id: "mq_066", text: "En başarılı insanlar B planında iyi olanlardır.", author: "James A. Yorke" },
  { id: "mq_067", text: "Birlikte çalıştığım tüm büyük performans sahiplerini kişisel bir hayal besler.", author: "John Eliot" },
  { id: "mq_068", text: "Kendine değer vermeden zamanına değer vermezsin. Zamanına değer vermeden de onu anlamlı kullanamazsın.", author: "M. Scott Peck" },
  { id: "mq_069", text: "İnsanı zenginleştiren, gerçeğe sahip olmak değil; onu ararken elde ettiği başarı ve bu arayışın verdiği mutluluktur.", author: "Max Planck" },
  { id: "mq_070", text: "Sen çalışmadıkça hiçbir şey işe yaramaz.", author: "Maya Angelou" },
  { id: "mq_071", text: "Kazanmak için sahip olunması gereken bir özellik vardır: amacın kesinliği, ne istediğini bilmek ve ona ulaşmak için yakıcı bir arzu duymak.", author: "Napoleon Hill" },
  { id: "mq_072", text: "Büyük insanların çoğu, en büyük başarılarına en büyük başarısızlıklarının yalnızca bir adım ötesinde ulaşmıştır.", author: "Napoleon Hill" },
  { id: "mq_073", text: "Başarı merdiveninin tepesi hiçbir zaman kalabalık değildir.", author: "Napoleon Hill" },
  { id: "mq_074", text: "Sana başarıyı kendinden başka hiçbir şeyin getiremeyeceğini hatırla.", author: "Napoleon Hill" },
  { id: "mq_075", text: "Eylem, bütün başarının temel anahtarıdır.", author: "Pablo Picasso" },
  { id: "mq_076", text: "Sanayi tarihi, değişen rekabet koşullarına stratejik bakışını uyarlayamayan bir zamanların başarılı şirketlerinin kalıntılarıyla doludur.", author: "Ralph Abernathy" },
  { id: "mq_077", text: "Coşku olmadan büyük hiçbir şey başarılmamıştır.", author: "Ralph Waldo Emerson" },
  { id: "mq_078", text: "Kendine güvenmek başarının ilk sırrıdır.", author: "Ralph Waldo Emerson" },
  { id: "mq_079", text: "Başarının sırrını kendine sor. Cevabını dinle ve onu uygula.", author: "Richard Bach" },
  { id: "mq_080", text: "Hayattaki pek çok başarısızlık, vazgeçtiklerinde başarıya ne kadar yakın olduklarını fark etmeyen insanlardır.", author: "Thomas Edison" },
  { id: "mq_081", text: "Sonuç mu? Elbette çok sonuç aldım. İşe yaramayan birkaç bin şey biliyorum.", author: "Thomas Edison" },
  { id: "mq_082", text: "Başarının ilk şartı, fiziksel ve zihinsel enerjini yorulmadan tek bir probleme sürekli uygulayabilmektir.", author: "Thomas Edison" },
  { id: "mq_083", text: "Başarı formülü: az söz ver, fazlasını teslim et.", author: "Tom Peters" },
  { id: "mq_084", text: "Başarılı insanlar daha iyi sorular sorar; bunun sonucunda daha iyi cevaplar alırlar.", author: "Tony Robbins" },
  { id: "mq_085", text: "Başarıya giden yol, büyük ve kararlı adımlar atmaktır.", author: "Tony Robbins" },
  { id: "mq_086", text: "Liderler doğmaz, yetişir. Her şey gibi onlar da çok çalışmayla oluşur. Her hedef için ödememiz gereken bedel budur.", author: "Vince Lombardi" },
  { id: "mq_087", text: "Peşinden gitme cesaretimiz varsa bütün hayallerimiz gerçek olabilir.", author: "Walt Disney" },
  { id: "mq_088", text: "Hayat oyununa sahip olduğu her şeyi vermeyen birinin başarılı olmasını hayal edemiyorum.", author: "Walter Cronkite" },
  { id: "mq_089", text: "Hayal etmekten fazlasını yap: çalış.", author: "William Arthur Ward" },
  { id: "mq_090", text: "Başarının anahtarı olan altı temel nitelik: samimiyet, kişisel dürüstlük, alçakgönüllülük, nezaket, bilgelik ve yardımseverlik.", author: "William C. Menninger" },
  { id: "mq_091", text: "Başarı, coşkuyu kaybetmeden bir başarısızlıktan diğerine ilerlemektir.", author: "Winston Churchill" },
  { id: "mq_092", text: "Başarı nihai değildir; başarısızlık ölümcül değildir. Önemli olan devam etme cesaretidir.", author: "Winston Churchill" },
];
