import type { ManifestQuote } from "./types";

export const QUOTES2: ManifestQuote[] = [
  { id: "mq_093", text: "Başarının yüzde sekseni ortaya çıkmaktır.", author: "Woody Allen" },
  { id: "mq_094", text: "Bilgelik ve kavrayış, emeklilik ve boş zamanın değil, deneyimin meyvesidir. Büyük ihtiyaçlar büyük erdemleri ortaya çıkarır.", author: "Abigail Adams" },
  { id: "mq_095", text: "Karakter bir ağaç, itibar ise onun gölgesi gibidir. Gölge bizim ne düşündüğümüzdür; ağaç ise gerçeğin kendisidir.", author: "Abraham Lincoln" },
  { id: "mq_096", text: "Çoğu insan, mutlu olmaya ne kadar karar verirse o kadar mutludur.", author: "Abraham Lincoln" },
  { id: "mq_097", text: "Geleceğin en güzel yanı, her seferinde yalnızca bir gün gelmesidir.", author: "Abraham Lincoln" },
  { id: "mq_098", text: "Bir fili arka ayaklarından tutmuşsan ve kaçmaya çalışıyorsa, onu bırakmak en iyisidir.", author: "Abraham Lincoln" },
  { id: "mq_099", text: "Bütün insanları bir süre, bazı insanları her zaman kandırabilirsin; ama bütün insanları her zaman kandıramazsın.", author: "Abraham Lincoln" },
  { id: "mq_100", text: "Yaşlı insanların bile bilgelik öğrenmesi iyidir.", author: "Aeschylus" },
  { id: "mq_101", text: "Bilgelik yalnızca acı çekerek gelir.", author: "Aeschylus" },
  { id: "mq_102", text: "Takdir, duanın en yüce biçimidir; çünkü şükran dolu düşüncelerinin ışığını tuttuğun her yerde iyiliğin varlığını kabul eder.", author: "Alan Cohen" },
  { id: "mq_103", text: "Şimdiyi yaşama kapasitesi olmayanlar gelecek için geçerli planlar yapamaz.", author: "Alan Watts" },
  { id: "mq_104", text: "İnsan, olması gerektiğini düşündüğü şeyi değil, gerçekten olanı aramalıdır.", author: "Albert Einstein" },
  { id: "mq_105", text: "Büyük fikirler çoğu zaman sıradan zihinlerin sert muhalefetiyle karşılaşır.", author: "Albert Einstein" },
  { id: "mq_106", text: "Sade ve gösterişsiz bir yaşam biçiminin hem beden hem zihin için herkes adına en iyisi olduğuna inanıyorum.", author: "Albert Einstein" },
  { id: "mq_107", text: "Geleceği hiç düşünmem. Zaten yeterince çabuk gelir.", author: "Albert Einstein" },
  { id: "mq_108", text: "Barış güç kullanılarak korunamaz. Ona yalnızca anlayışla ulaşılabilir.", author: "Albert Einstein" },
  { id: "mq_109", text: "Bilgelikle gücü birleştirme çabası çok nadiren başarılı olmuş, olduğunda da kısa sürmüştür.", author: "Albert Einstein" },
  { id: "mq_110", text: "Başarılı bir insan olmaya değil, değerli bir insan olmaya çalış.", author: "Albert Einstein" },
  { id: "mq_111", text: "Sorunlarımızı, onları yaratırken kullandığımız aynı düşünce biçimiyle çözemeyiz.", author: "Albert Einstein" },
  { id: "mq_112", text: "İnsanlığın bütün bilgeliği iki kelimede özetlenir: bekle ve umut et.", author: "Alexandre Dumas" },
  { id: "mq_113", text: "Hayatta kolayca kaymanın iki yolu vardır: her şeye inanmak ya da her şeyden şüphe etmek. İkisi de bizi düşünmekten kurtarır.", author: "Alfred Korzybski" },
  { id: "mq_114", text: "Yaş ilerledikçe bilgelik gelir; asıl bilgelik ise hayatın sunduklarından keyif almayı bilmektir.", author: "Amber Valletta" },
  { id: "mq_115", text: "İlk görüşte aşkı anlamak kolaydır; asıl mucize, iki insanın bir ömür birbirine baktıktan sonra da sevgiyi sürdürebilmesidir.", author: "Amy Bloom" },
  { id: "mq_116", text: "Hayaller eylemin gerçeğine dönüşür. Eylemlerden yeniden hayal doğar; bu karşılıklı bağ yaşamın en yüksek biçimini yaratır.", author: "Anaïs Nin" },
  { id: "mq_117", text: "Hayat, insanın cesareti ölçüsünde daralır ya da genişler.", author: "Anaïs Nin" },
  { id: "mq_118", text: "Bilgiye sahip olmak hayranlık ve gizem duygusunu öldürmez. Her zaman daha fazla gizem vardır.", author: "Anaïs Nin" },
  { id: "mq_119", text: "Coşkunun çılgınlığını, bilgeliğin kayıtsızlığına tercih ederim.", author: "Anatole France" },
  { id: "mq_120", text: "İroni, düşüncenin neşesi ve bilgeliğin sevincidir.", author: "Anatole France" },
  { id: "mq_121", text: "Büyük işler başarmak için harekete geçmenin yanında hayal de kurmalıyız.", author: "Anatole France" },
  { id: "mq_122", text: "Konuşmayı konuşarak, çalışmayı çalışarak, koşmayı koşarak, işi yaparak öğrenirsin; aynı şekilde sevmeyi de severek öğrenirsin.", author: "Anatole France" },
  { id: "mq_123", text: "Zamanın bir şeyleri değiştirdiği söylenir; ama aslında onları değiştirmesi gereken sensin.", author: "Andy Warhol" },
  { id: "mq_124", text: "Kış olmasaydı bahar bu kadar güzel olmazdı; zaman zaman zorluk tatmasaydık refah bu kadar değerli gelmezdi.", author: "Anne Bradstreet" },
  { id: "mq_125", text: "Zamanla biriken bilgeliğim bana her deneyimin bir keşif biçimi olduğunu öğretti.", author: "Ansel Adams" },
  { id: "mq_126", text: "Bilgiyi uygulamaya koymadıkça onun hiçbir değeri yoktur.", author: "Anton Chekhov" },
  { id: "mq_127", text: "Bir düşünceyi kabul etmeden önce zihninde tartabilmek, eğitimli bir zihnin işaretidir.", author: "Aristotle" },
  { id: "mq_128", text: "Zihnin enerjisi yaşamın özüdür.", author: "Aristotle" },
  { id: "mq_129", text: "Adalet erdemi, bilgeliğin düzenlediği ölçülülükte yatar.", author: "Aristotle" },
  { id: "mq_130", text: "Eylemde büyük bir yürek, işte ise güçlü bir zihin en önemli niteliktir.", author: "Arthur Schopenhauer" },
  { id: "mq_131", text: "Güzel gözler için başkalarındaki iyiliği ara; güzel sözler için yalnızca nezaket konuş; dengeli yürümek için asla yalnız olmadığını bil.", author: "Audrey Hepburn" },
  { id: "mq_132", text: "Sabır, bilgeliğin yol arkadaşıdır.", author: "Augustine of Hippo" },
  { id: "mq_133", text: "Cesaret olmadan bilgelik meyve vermez.", author: "Baltasar Gracián" },
  { id: "mq_134", text: "Başka birini ya da başka bir zamanı beklersek değişim gelmez. Beklediğimiz kişiler biziz; aradığımız değişim biziz.", author: "Barack Obama" },
  { id: "mq_135", text: "Doğru yolda yürüyorsan ve yürümeye devam etmeye hazırsan sonunda ilerlersin.", author: "Barack Obama" },
  { id: "mq_136", text: "Bilgelik hiçbir grubun tekelinde değildir. Uzlaşma olmadan hiçbir demokrasi işlemez.", author: "Barack Obama" },
  { id: "mq_137", text: "Kendimizi yeniden keşfetmek ve hayatımızı içtenlikle yaşamak istiyorsak bize hizmet etmeyen şeylere ve insanlara hayır deme cesaretini bulmalıyız.", author: "Barbara De Angelis" },
  { id: "mq_138", text: "Eylem her zaman mutluluk getirmeyebilir; ama eylem olmadan mutluluk yoktur.", author: "Benjamin Disraeli" },
  { id: "mq_139", text: "Hayatı seviyor musun? Öyleyse zamanı boşa harcama; çünkü hayatın yapıldığı madde zamandır.", author: "Benjamin Franklin" },
  { id: "mq_140", text: "Deneyim pahalı bir okuldur; ama bazı insanlar başka hiçbir yerde öğrenmez.", author: "Benjamin Franklin" },
  { id: "mq_141", text: "Bana söyle, unuturum. Bana öğret, hatırlarım. Beni dahil et, öğrenirim.", author: "Benjamin Franklin" },
  { id: "mq_142", text: "Bilgeliğin kapıları hiçbir zaman kapanmaz.", author: "Benjamin Franklin" },
  { id: "mq_143", text: "Bilgelik tapınağının eşiği, kendi bilgisizliğimizi bilmektir.", author: "Benjamin Franklin" },
  { id: "mq_144", text: "Düşünce özgürlüğü olmadan bilgelik; ifade özgürlüğü olmadan da gerçek özgürlük olamaz.", author: "Benjamin Franklin" },
  { id: "mq_145", text: "Kendine güven. Sandığından daha fazlasını biliyorsun.", author: "Benjamin Spock" },
  { id: "mq_146", text: "Sahte bilgiden sakın; bilgisizlikten daha tehlikelidir.", author: "Bernard Shaw" },
  { id: "mq_147", text: "Bizi bilgeleştiren geçmişi hatırlamak değil, geleceğe karşı duyduğumuz sorumluluktur.", author: "Bernard Shaw" },
  { id: "mq_148", text: "Korkuyu yenmek bilgeliğin başlangıcıdır.", author: "Bertrand Russell" },
  { id: "mq_149", text: "Hayal gücü, öngörülebilir olandan kaçmamızı sağlar. 'Uçamazsın' diyen genel kabule 'Sadece izle!' diye cevap verebilmemizi mümkün kılar.", author: "Bill Bradley" },
  { id: "mq_150", text: "Sınırlarımızı öğrenmeliyiz. Hepimiz bir şeyiz ama hiçbirimiz her şey değiliz.", author: "Blaise Pascal" },
  { id: "mq_151", text: "Bilgisizliğe kapılmamak bilgeliktir.", author: "Bodhidharma" },
  { id: "mq_152", text: "Domatesin meyve olduğunu bilmek bilgidir; onu meyve salatasına koymamak ise bilgeliktir.", author: "Brian O\\u0027Driscoll" },
  { id: "mq_153", text: "Hedefler, başarının fırınındaki yakıttır.", author: "Brian Tracy" },
  { id: "mq_154", text: "Her şeyi yapmak için hiçbir zaman yeterli zaman yoktur; ama en önemli şeyi yapmak için her zaman yeterli zaman vardır.", author: "Brian Tracy" },
  { id: "mq_155", text: "Yeni bir şey denerken tuhaf ve rahatsız hissetmeye razıysan büyüyebilirsin.", author: "Brian Tracy" },
  { id: "mq_156", text: "Bilge bir insan, aptalca bir sorudan; aptal birinin bilgece bir cevaptan öğrenebileceğinden daha fazlasını öğrenebilir.", author: "Bruce Lee" },
  { id: "mq_157", text: "Hayatı seviyorsan zamanı boşa harcama; çünkü hayat zamandan oluşur.", author: "Bruce Lee" },
  { id: "mq_158", text: "Bir şeyi düşünmek için çok fazla zaman harcarsan onu asla bitiremezsin.", author: "Bruce Lee" },
  { id: "mq_159", text: "Hataları kabul edecek cesaret varsa hatalar her zaman affedilebilir.", author: "Bruce Lee" },
  { id: "mq_160", text: "Gereksiz çaba azaldıkça daha hızlı ve daha güçlü olursun.", author: "Bruce Lee" },
  { id: "mq_161", text: "Kendini tanımak, başkalarıyla etkileşim içindeyken kendi davranışlarını incelemektir.", author: "Bruce Lee" },
  { id: "mq_162", text: "Bilgi yalnızca gerçeğin değil, hataların da üzerinde yükselir.", author: "Carl Jung" },
  { id: "mq_163", text: "Dışarıya bakan hayal kurar, içine bakan uyanır.", author: "Carl Jung" },
  { id: "mq_164", text: "Hayal gücüyle oynama olmadan hiçbir yaratıcı çalışma doğmamıştır. Hayal gücünün oyununa borcumuz ölçülemez.", author: "Carl Jung" },
  { id: "mq_165", text: "Vizyonun ancak kendi kalbine bakabildiğinde netleşir. Dışarıya bakan hayal kurar, içine bakan uyanır.", author: "Carl Jung" },
  { id: "mq_166", text: "Vizyonun ancak kalbine baktığında berraklaşır. Dışarıya bakan hayal kurar; içine bakan uyanır.", author: "Carl Jung" },
  { id: "mq_167", text: "Önce hayal etmeden hiçbir şey gerçekleşmez.", author: "Carl Sandburg" },
  { id: "mq_168", text: "Sır, neye vurgu yaptığımızdadır. Kendimizi ya mutsuz ederiz ya da mutlu. İkisinin de harcadığı emek aynıdır.", author: "Carlos Castaneda" },
  { id: "mq_169", text: "Aklın bilgeliği vardır, bir de kalbin bilgeliği.", author: "Charles Dickens" },
  { id: "mq_170", text: "Bildiğim en büyük zevk, iyi bir işi gizlice yapmak ve onun tesadüfen fark edilmesidir.", author: "Charles Lamb" },
  { id: "mq_171", text: "Hayat; geçmişin birikimi, şimdinin farkındalığı ve bilginin ötesindeki geleceğin işaretidir.", author: "Charles Lindbergh" },
  { id: "mq_172", text: "İmkânsızlıklar, henüz öğrenmediğimiz şeylerden ibarettir.", author: "Charles W. Chesnutt" },
  { id: "mq_173", text: "Karmakarışık bir zihin huzursuz bir yastık yaratır.", author: "Charlotte Brontë" },
  { id: "mq_174", text: "En yükseğe saygı duyalım; ama dimdik ve gözlerimiz açık. Geçmişe değil geleceğe bakalım.", author: "Charlotte Perkins Gilman" },
  { id: "mq_175", text: "Ültimatomları, yerleşik kabulleri ve mutlak doğruları sorgulamadan kabul etme.", author: "Christopher Reeve" },
  { id: "mq_176", text: "İnsanlar çoğu zaman yapamayacaklarının olumsuz tarafına bakar. Ben her zaman yapabileceklerimin olumlu tarafına bakarım.", author: "Chuck Norris" },
  { id: "mq_177", text: "Bilgeliğin görevi iyiyle kötüyü ayırt etmektir.", author: "Cicero" },
  { id: "mq_178", text: "Büyük işlerde mükemmelliğe ulaşmak istiyorsan küçük işlerde mükemmellik alışkanlığı geliştir. Mükemmellik istisna değil, sürekli bir tutumdur.", author: "Colin Powell" },
  { id: "mq_179", text: "Bilgeliği üç yoldan öğrenebiliriz: düşünerek, ki en soylusudur; taklit ederek, ki en kolayıdır; deneyimle, ki en acısıdır.", author: "Confucius" },
  { id: "mq_180", text: "Düşünmeden öğrenmek boşa emektir; öğrenmeden düşünmek tehlikelidir.", author: "Confucius" },
  { id: "mq_181", text: "En büyük şanımız hiç düşmemek değil, her düştüğümüzde yeniden ayağa kalkmaktır.", author: "Confucius" },
  { id: "mq_182", text: "Öğrendiklerini tekrar gözden geçirip yeni şeyler öğrenen kişi öğretmeye hazırdır.", author: "Confucius" },
  { id: "mq_183", text: "Geleceği anlamak istiyorsan geçmişi incele.", author: "Confucius" },
];
