import type { ManifestQuote } from "./types";

export const QUOTES3: ManifestQuote[] = [
  { id: "mq_184", text: "Üstün insan önce yapar, sonra konuşur; konuşması da yaptıklarıyla uyumlu olur.", author: "Confucius" },
  { id: "mq_185", text: "Üstün insan sözlerinde alçakgönüllü, eylemlerinde ise güçlüdür.", author: "Confucius" },
  { id: "mq_186", text: "Mutlulukta ve bilgelikte istikrarlı kalmak isteyenler çoğu zaman değişmek zorundadır.", author: "Confucius" },
  { id: "mq_187", text: "İnsanlara karşı görevlerini içtenlikle yerine getirip manevi olana saygı duyarken ondan ölçülü biçimde uzak durmak bilgelik sayılabilir.", author: "Confucius" },
  { id: "mq_188", text: "Çalışıp düşünmemek boşa emektir. Düşünüp çalışmamak ise tehlikelidir.", author: "Confucius" },
  { id: "mq_189", text: "Hedeflere ulaşılamayacağı açıksa hedefleri değil, atacağın adımları değiştir.", author: "Confucius" },
  { id: "mq_190", text: "İyi bir insan gördüğünde ona benzemeyi düşün. İyi olmayan birini gördüğünde kendi zayıf yönlerini gözden geçir.", author: "Confucius" },
  { id: "mq_191", text: "Değerli birini gördüğünde ona nasıl benzeyebileceğini düşün; değersiz birini gördüğünde kendini sorgula.", author: "Confucius" },
  { id: "mq_192", text: "Bilgelik, merhamet ve cesaret insanlığın evrensel olarak kabul gören üç ahlaki niteliğidir.", author: "Confucius" },
  { id: "mq_193", text: "Olabileceğin kişi olmayı istemek, yaşamın amaçlarından biridir.", author: "Cynthia Ozick" },
  { id: "mq_194", text: "Gerçek mutluluk, koşullar ne kadar zor olursa olsun yenilmeyen güçlü bir ruh inşa etmektir.", author: "Daisaku Ikeda" },
  { id: "mq_195", text: "Kendi sorunlarının ötesine geçip başkalarıyla ilgilendiğinde içsel güç, özgüven, cesaret ve daha büyük bir sakinlik kazanırsın.", author: "Dalai Lama" },
  { id: "mq_196", text: "Mutluluk hazır gelen bir şey değildir. Kendi eylemlerinden doğar.", author: "Dalai Lama" },
  { id: "mq_197", text: "Temelde birbirimize benzediğimize ve aynı temel potansiyele sahip olduğumuza inanıyorum.", author: "Dalai Lama" },
  { id: "mq_198", text: "En karanlık günlerde umut, en aydınlık günlerde odak bulurum. Evreni yargılamam.", author: "Dalai Lama" },
  { id: "mq_199", text: "İnsanlar başkalarının duygularına ve mutluluğuna kayıtsız kaldıkça gerçek iş birliği ruhuna ulaşmak zordur.", author: "Dalai Lama" },
  { id: "mq_200", text: "Bazen istediğin şeyi elde edememenin olağanüstü bir şans olabileceğini hatırla.", author: "Dalai Lama" },
  { id: "mq_201", text: "Olumlu tarafı ve potansiyeli gör; ardından çaba göster.", author: "Dalai Lama" },
  { id: "mq_202", text: "Kalbimizi ve zihnimizi dönüştürmenin anahtarı, düşünce ve duygularımızın nasıl çalıştığını anlamaktır.", author: "Dalai Lama" },
  { id: "mq_203", text: "En önemli şey zihnimizi dönüştürmektir: yeni bir düşünme biçimi, yeni bir bakış açısı ve yeni bir iç dünya geliştirmeye çalışmalıyız.", author: "Dalai Lama" },
  { id: "mq_204", text: "Dünyadaki önemli şeylerin çoğu, hiç umut kalmamış gibi görünürken bile denemeye devam eden insanlar tarafından başarılmıştır.", author: "Dale Carnegie" },
  { id: "mq_205", text: "Kader bize limon verirse limonata yapmaya çalışalım.", author: "Dale Carnegie" },
  { id: "mq_206", text: "En iyi derslerimizin bazılarını geçmişteki hatalardan öğreniriz. Geçmişin hatası geleceğin bilgeliği ve başarısı olabilir.", author: "Dale Turner" },
  { id: "mq_207", text: "Keşfin önündeki en büyük engel bilgisizlik değil, bilgi sahibi olduğumuz yanılsamasıdır.", author: "Daniel J. Boorstin" },
  { id: "mq_208", text: "Bilgelik sona baktığında başlar.", author: "Daniel Webster" },
  { id: "mq_209", text: "Sözlerin dağları yerinden oynatmadığını bilmek önemlidir. Dağları hareket ettiren şey emektir, hem de titiz emek.", author: "Danilo Dolci" },
  { id: "mq_210", text: "Bir şey öğrendiğin hiçbir gün tamamen kayıp değildir.", author: "David Eddings" },
  { id: "mq_211", text: "Küçük fırsatlar çoğu zaman büyük girişimlerin başlangıcıdır.", author: "Demosthenes" },
  { id: "mq_212", text: "Korku karanlıkta büyür; çevrende bir canavar olduğunu düşünüyorsan ışığı yak.", author: "Dorothy Thompson" },
  { id: "mq_213", text: "Ancak korkmayı bıraktığımızda gerçekten yaşamaya başlarız.", author: "Dorothy Thompson" },
  { id: "mq_214", text: "Bilgelik, konuşmayı tercih ettiğin zamanlarda dinleyerek geçirdiğin bir ömrün ödülüdür.", author: "Doug Larson" },
  { id: "mq_215", text: "Başkalarının deneyimlerinden öğrenme yeteneğiyle neredeyse benzersiz olan insanlar, bunu yapmaya karşı şaşırtıcı bir isteksizlik de gösterebilir.", author: "Douglas Adams" },
  { id: "mq_216", text: "Gerçeklik sonunda hayallerinden daha güzel olduğu için uyuyamadığında sevginin ne olduğunu anlarsın.", author: "Dr. Seuss" },
  { id: "mq_217", text: "Büyümek ve gerçekten olduğun kişi olmak cesaret ister.", author: "E. E. Cummings" },
  { id: "mq_218", text: "İnsan acısının büyük bölümü gereksizdir. Fark edilmeden çalışan zihin hayatını yönettiği sürece bu acıyı insan kendi yaratır.", author: "Eckhart Tolle" },
  { id: "mq_219", text: "İyi olmaya çalışarak değil, zaten içinde bulunan iyiliği keşfederek iyi olursun.", author: "Eckhart Tolle" },
  { id: "mq_220", text: "Gördüğümüz ya da göründüğünü sandığımız her şey, bir rüyanın içindeki rüyadan ibarettir.", author: "Edgar Allan Poe" },
  { id: "mq_221", text: "Gündüz hayal kuranlar, yalnızca gece rüya görenlerin kaçırdığı birçok şeyin farkındadır.", author: "Edgar Allan Poe" },
  { id: "mq_222", text: "Mutlu olmaya bu kadar çok uğraşmayı bıraksak aslında oldukça iyi vakit geçirebiliriz.", author: "Edith Wharton" },
  { id: "mq_223", text: "Hayat tek gerçek danışmandır; kişisel deneyimden süzülmeyen bilgelik karakterimizin bir parçası hâline gelmez.", author: "Edith Wharton" },
  { id: "mq_224", text: "Bilgelik ve erdem olmadan özgürlük nedir? Eğitimsiz ve sınırsız bırakılmışsa, mümkün olan en büyük kötülüklerden birine dönüşebilir.", author: "Edmund Burke" },
  { id: "mq_225", text: "Her dikenin üzerinde hoş bir bilgelik büyür, her küçük dereden tatlı bir ders akar.", author: "Edward Young" },
  { id: "mq_226", text: "Meditasyonla ve her seferinde tek bir şeye tam dikkatimizi vererek, dikkatimizi seçtiğimiz yere yönlendirmeyi öğrenebiliriz.", author: "Eknath Easwaran" },
  { id: "mq_227", text: "Başarısız kişi hata yapan değil, hatasından yararlanmayı başaramayan kişidir.", author: "Elbert Hubbard" },
  { id: "mq_228", text: "Her insan her gün en az birkaç dakika aptallık eder; bilgelik bu sınırı aşmamaktır.", author: "Elbert Hubbard" },
  { id: "mq_229", text: "Vazgeçmek dışında başarısızlık yoktur.", author: "Elbert Hubbard" },
  { id: "mq_230", text: "Büyük zihinler fikirleri, orta zihinler olayları, küçük zihinler insanları konuşur.", author: "Eleanor Roosevelt" },
  { id: "mq_231", text: "Sanırım bir şekilde gerçekten kim olduğumuzu öğrenir ve sonra o kararla yaşamaya başlarız.", author: "Eleanor Roosevelt" },
  { id: "mq_232", text: "Gelecek, hayallerinin güzelliğine inananlara aittir.", author: "Eleanor Roosevelt" },
  { id: "mq_233", text: "Yapamayacağını düşündüğün şeyleri yapmalısın.", author: "Eleanor Roosevelt" },
  { id: "mq_234", text: "Seçimlerimizden yalnızca kendimizin sorumlu olduğuna inanıyorum; hayatımız boyunca her eylemin, sözün ve düşüncenin sonuçlarını kabul etmeliyiz.", author: "Elisabeth Kübler-Ross" },
  { id: "mq_235", text: "Seven kişi imkânsıza inanır.", author: "Elizabeth Browning" },
  { id: "mq_236", text: "En gerçek büyüklük iyilikte, en gerçek bilgelik ise mutlu bir zihindedir.", author: "Ella Wheeler Wilcox" },
  { id: "mq_237", text: "Zaten bildiğini düşündüğü şeyi insanın öğrenmesi imkânsızdır.", author: "Epictetus" },
  { id: "mq_238", text: "Önce küçük şeylerde kendini geliştir; sonra daha büyüklerine geç.", author: "Epictetus" },
  { id: "mq_239", text: "Birinin hatasına öfkelendiğinde kendine dön ve kendi kusurlarını incele. O zaman öfkeni unutursun.", author: "Epictetus" },
  { id: "mq_240", text: "Hareketi eylemle karıştırma.", author: "Ernest Hemingway" },
  { id: "mq_241", text: "Bazen bütün bir günün en önemli anı, iki derin nefes arasında verdiğimiz moladır.", author: "Etty Hillesum" },
  { id: "mq_242", text: "Başarıyla birlikte bilgelik ünü de gelir.", author: "Euripides" },
  { id: "mq_243", text: "Zekilik bilgelik değildir.", author: "Euripides" },
  { id: "mq_244", text: "Değişmez ve katı ilkeleri olan biriyim; bunların ilki her zaman esnek olmaktır.", author: "Everett Dirksen" },
  { id: "mq_245", text: "Sonsuz bilgelik ve sonsuz iyilikle yönetilen bir düzen, mümkün olan yönetim biçimlerinin en kusursuzudur.", author: "Ezra Stiles" },
  { id: "mq_246", text: "Yerinde sorulmuş bir soru bilgeliğin yarısıdır.", author: "Francis Bacon" },
  { id: "mq_247", text: "Sessizlik, bilgeliği besleyen uykudur.", author: "Francis Bacon" },
  { id: "mq_248", text: "Saf ve kutsal sadelik, bu dünyanın bütün gösterişli bilgeliğini şaşırtır.", author: "Francis of Assisi" },
  { id: "mq_249", text: "Yardımseverlik ve bilgelik olan yerde ne korku ne de bilgisizlik vardır.", author: "Francis of Assisi" },
  { id: "mq_250", text: "Hepimiz büyürüz. Umarım daha bilge oluruz. Yaş deneyim getirir; ebeveynlik ise insanın hayatını bütünüyle değiştirir.", author: "Frank Abagnale" },
  { id: "mq_251", text: "Bilginin başlangıcı, anlamadığımız bir şeyi keşfetmektir.", author: "Frank Herbert" },
  { id: "mq_252", text: "Saygı yıllarla değil, davranışlarla kazanılmalıdır.", author: "Frank Lloyd Wright" },
  { id: "mq_253", text: "Gerçekten inandığın şey gerçekleşme eğilimindedir; bir şeye duyduğun inanç onun gerçekleşmesini mümkün kılar.", author: "Frank Lloyd Wright" },
  { id: "mq_254", text: "Mutluluk yalnızca para sahibi olmakta değildir; başarmanın sevincinde ve yaratıcı çabanın heyecanındadır.", author: "Franklin D. Roosevelt" },
  { id: "mq_255", text: "Bir yöntem seçip denemek sağduyudur. İşe yaramazsa bunu dürüstçe kabul et ve başka bir yöntem dene. Ama her şeyden önce bir şey dene.", author: "Franklin D. Roosevelt" },
  { id: "mq_256", text: "İşlenmemiş deha şimşeğe benzer; bilgelik ise güneş gibidir.", author: "Franz Grillparzer" },
  { id: "mq_257", text: "Mücadele yoksa ilerleme de yoktur.", author: "Frederick Douglass" },
  { id: "mq_258", text: "Bilgelik bazen yeryüzünde, leş kokusundan ilham alan bir kuzgun gibi mi belirir?", author: "Friedrich Nietzsche" },
  { id: "mq_259", text: "Bilgi sahibi insan yalnızca düşmanlarını sevebilmeyi değil, gerektiğinde dostlarını eleştirebilmeyi de bilmelidir.", author: "Friedrich Nietzsche" },
  { id: "mq_260", text: "Bedeninde, en derin felsefenden daha fazla bilgelik vardır.", author: "Friedrich Nietzsche" },
  { id: "mq_261", text: "İnsan ne yaparsa yapsın üzerine çöken bir kadere inanmam; ama harekete geçmezse insanın başına gelebilecek bir kadere inanırım.", author: "G. K. Chesterton" },
  { id: "mq_262", text: "İnsanlar ne yaparsa yapsın başlarına gelen bir kadere inanmam; fakat harekete geçmezlerse başlarına gelebilecek bir kadere inanırım.", author: "G. K. Chesterton" },
  { id: "mq_263", text: "Yaşarken kaybettiğimiz hayat nerede? Bilgide kaybettiğimiz bilgelik nerede? Bilgide kaybettiğimiz bilgi nerede?", author: "George Eliot" },
  { id: "mq_264", text: "İnanılan efsaneler zamanla gerçeğe dönüşme eğilimindedir.", author: "George Orwell" },
  { id: "mq_265", text: "Tarihten ders alamayanlar onu tekrar etmeye mahkûmdur.", author: "George Santayana" },
  { id: "mq_266", text: "Hayal gücünün sıçrayışları ve hayaller olmadan olasılıkların heyecanını kaybederiz. Sonuçta hayal kurmak da bir planlama biçimidir.", author: "Gloria Steinem" },
  { id: "mq_267", text: "Nezaketimiz, inandığımız şey için en ikna edici kanıt olabilir.", author: "Gordon Hinckley" },
  { id: "mq_268", text: "Hayatlarımız, neye ve kime inandığımızın en anlamlı ifadesidir. Gerçek zenginliğimiz de inancımızda yatar.", author: "Gordon Hinckley" },
  { id: "mq_269", text: "Karakterimiz, kimsenin bakmadığını düşündüğümüzde yaptığımız şeydir.", author: "H. Jackson Brown Jr." },
  { id: "mq_270", text: "Büyük düşün ama küçük zevklerin de tadını çıkar.", author: "H. Jackson Brown Jr." },
  { id: "mq_271", text: "Her şeyi bilmekten çok, öğrendiklerimizin değerini bilmek önemlidir.", author: "Hannah More" },
  { id: "mq_272", text: "Engeller, gözlerini hedeften ayırdığında gördüğün şeylerdir.", author: "Hannah More" },
  { id: "mq_273", text: "Yoksul insan parası olmayan değil, hayali olmayan kişidir.", author: "Harry Kemp" },
  { id: "mq_274", text: "Eksiklerinle yüzleş ve onları kabul et; ama sana hükmetmelerine izin verme. Sana sabrı, anlayışı ve içgörüyü öğretsinler.", author: "Helen Keller" },
];
