import type { ManifestQuote } from "./types";

export const QUOTES4: ManifestQuote[] = [
  { id: "mq_275", text: "We could never learn to be brave and patient if there were only joy in the world.", author: "Helen Keller" },
  { id: "mq_276", text: "The eye sees only what the mind is prepared to comprehend.", author: "Henri Bergson" },
  { id: "mq_277", text: "Think like a man of action; act like a man of thought.", author: "Henri Bergson" },
  { id: "mq_278", text: "Work while you have the light. You are responsible for the talent that has been entrusted to you.", author: "Henri-Frédéric Amiel" },
  { id: "mq_279", text: "All this worldly wisdom was once the unamiable heresy of some wise man.", author: "Henry David Thoreau" },
  { id: "mq_280", text: "Ignorance and bungling with love are better than wisdom and skill without.", author: "Henry David Thoreau" },
  { id: "mq_281", text: "It is a characteristic of wisdom not to do desperate things.", author: "Henry David Thoreau" },
  { id: "mq_282", text: "If you think you can, you can. And if you think you can\u0027t, you\u0027re right.", author: "Henry Ford" },
  { id: "mq_283", text: "Obstacles are those frightful things you see when you take your eyes off your goal.", author: "Henry Ford" },
  { id: "mq_284", text: "Trouble is only opportunity in work clothes.", author: "Henry J. Kaiser" },
  { id: "mq_285", text: "Do not mind anything that anyone tells you about anyone else. Judge everyone and everything for yourself.", author: "Henry James" },
  { id: "mq_286", text: "Be glad of life because it gives you the chance to love, to work, to play, and to look up at the stars.", author: "Henry van Dyke Jr." },
  { id: "mq_287", text: "Wisdom often times consists of knowing what to do next.", author: "Herbert Hoover" },
  { id: "mq_288", text: "Wisdom is nothing but a preparation of the soul, a capacity, a secret art of thinking, feeling and breathing thoughts of unity at every moment of life.", author: "Hermann Hesse" },
  { id: "mq_289", text: "If you have the guts to keep making mistakes, your wisdom and intelligence leap forward with huge momentum.", author: "Holly Near" },
  { id: "mq_290", text: "A heart well prepared for adversity in bad times hopes, and in good times fears for a change in fortune.", author: "Horace" },
  { id: "mq_291", text: "Begin, be bold, and venture to be wise.", author: "Horace" },
  { id: "mq_292", text: "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason.", author: "Immanuel Kant" },
  { id: "mq_293", text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant" },
  { id: "mq_294", text: "We can only learn to love by loving.", author: "Iris Murdoch" },
  { id: "mq_295", text: "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", author: "Isaac Asimov" },
  { id: "mq_296", text: "The wisdom of the wise, and the experience of ages, may be preserved by quotation.", author: "Isaac D\u0027Israeli" },
  { id: "mq_297", text: "The only true wisdom is in knowing you know nothing.", author: "Isocrates" },
  { id: "mq_298", text: "True knowledge exists in knowing that you know nothing.", author: "Isocrates" },
  { id: "mq_299", text: "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.", author: "Isocrates" },
  { id: "mq_300", text: "The world is round and the place which may seem like the end may also be the beginning.", author: "Ivy Baker Priest" },
  { id: "mq_301", text: "We are either progressing or retrograding all the while. There is no such thing as remaining stationary in this life.", author: "James Freeman Clarke" },
  { id: "mq_302", text: "Nothing could be worse than the fear that one had given up too soon and left one unexpended effort that might have saved the world.", author: "Jane Addams" },
  { id: "mq_303", text: "The opportunity for brotherhood presents itself every time you meet a human being.", author: "Jane Wyman" },
  { id: "mq_304", text: "In complete darkness we are all the same, it is only our knowledge and wisdom that separates us, don\u0027t let your eyes deceive you.", author: "Janet Jackson" },
  { id: "mq_305", text: "A leader or a man of action in a crisis almost always acts subconsciously and then thinks of the reasons for his action.", author: "Jawaharlal Nehru" },
  { id: "mq_306", text: "The extreme limit of wisdom, that\u0027s what the public calls madness.", author: "Jean Cocteau" },
  { id: "mq_307", text: "Sadness flies away on the wings of time.", author: "Jean de La Fontaine" },
  { id: "mq_308", text: "What wisdom can you find that is greater than kindness?", author: "Jean-Jacques Rousseau" },
  { id: "mq_309", text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { id: "mq_310", text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix" },
  { id: "mq_311", text: "Correction does much, but encouragement does more.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_312", text: "If you must tell me your opinions, tell me what you believe in. I have plenty of doubts of my own.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_313", text: "Sometimes our fate resembles a fruit tree in winter. Who would think that those branches would turn green again and blossom, but we hope it, we know it.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_314", text: "Wisdom is found only in truth.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_315", text: "Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.", author: "John Adams" },
  { id: "mq_316", text: "Even youngish men can acquire wisdom as time goes by.", author: "John Bercow" },
  { id: "mq_317", text: "Wisdom cannot come by railroad or automobile or airplane or be hurried up by telegraph or telephone.", author: "John Burroughs" },
  { id: "mq_318", text: "The self is not something ready-made, but something in continuous formation through choice of action.", author: "John Dewey" },
  { id: "mq_319", text: "Without some goals and some efforts to reach it, no man can live.", author: "John Dewey" },
  { id: "mq_320", text: "The greater our knowledge increases the more our ignorance unfolds.", author: "John F. Kennedy" },
  { id: "mq_321", text: "The time to repair the roof is when the sun is shining.", author: "John F. Kennedy" },
  { id: "mq_322", text: "Those who dare to fail miserably can achieve greatly.", author: "John F. Kennedy" },
  { id: "mq_323", text: "I love you the more in that I believe you had liked me for my own sake and for nothing else.", author: "John Keats" },
  { id: "mq_324", text: "I will give you a definition of a proud man: he is a man who has neither vanity nor wisdom one filled with hatreds cannot be vain, neither can he be wise.", author: "John Keats" },
  { id: "mq_325", text: "Time you enjoy wasting, was not wasted.", author: "John Lennon" },
  { id: "mq_326", text: "Time you enjoyed wasting was not wasted.", author: "John Lennon" },
  { id: "mq_327", text: "You may say I\u0027m a dreamer, but I\u0027m not the only one, I hope someday you will join us, and the world will live as one.", author: "John Lennon" },
  { id: "mq_328", text: "I have always thought the actions of men the best interpreters of their thoughts.", author: "John Locke" },
  { id: "mq_329", text: "A day of worry is more exhausting than a day of work.", author: "John Lubbock" },
  { id: "mq_330", text: "The only real mistake is the one from which we learn nothing.", author: "John Powell" },
  { id: "mq_331", text: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.", author: "John Quincy Adams" },
  { id: "mq_332", text: "Quality is never an accident; it is always the result of intelligent effort.", author: "John Ruskin" },
  { id: "mq_333", text: "If we could learn to like ourselves, even a little, maybe our cruelties and angers might melt away.", author: "John Steinbeck" },
  { id: "mq_334", text: "It is a common experience that a problem difficult at night is resolved in the morning after the committee of sleep has worked on it.", author: "John Steinbeck" },
  { id: "mq_335", text: "Dreams come true. Without that possibility, nature would not incite us to have them.", author: "John Updike" },
  { id: "mq_336", text: "Never mistake activity for achievement.", author: "John Wooden" },
  { id: "mq_337", text: "You can\u0027t stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn" },
  { id: "mq_338", text: "Intuition will tell the thinking mind where to look next.", author: "Jonas Salk" },
  { id: "mq_339", text: "Discovery consists of seeing what everybody has seen and thinking what nobody else has thought.", author: "Jonathan Swift" },
  { id: "mq_340", text: "When we quit thinking primarily about ourselves and our own self-preservation, we undergo a truly heroic transformation of consciousness.", author: "Joseph Campbell" },
  { id: "mq_341", text: "He who has imagination without learning has wings but no feet.", author: "Joseph Joubert" },
  { id: "mq_342", text: "As you walk in God\u0027s divine wisdom, you will surely begin to see a greater measure of victory and good success in your life.", author: "Joseph Prince" },
  { id: "mq_343", text: "I believe in one thing only, the power of human will.", author: "Joseph Stalin" },
  { id: "mq_344", text: "Wisdom has never made a bigot, but learning has.", author: "Josh Billings" },
  { id: "mq_345", text: "Many sophisticated, intelligent people lack wisdom and common sense.", author: "Joyce Meyer" },
  { id: "mq_346", text: "Vanity can easily overtake wisdom. It usually overtakes common sense.", author: "Julian Casablancas" },
  { id: "mq_347", text: "A little knowledge that acts is worth infinitely more than much knowledge that is idle.", author: "Kahlil Gibran" },
  { id: "mq_348", text: "Keep me away from the wisdom which does not cry, the philosophy which does not laugh and the greatness which does not bow before children.", author: "Kahlil Gibran" },
  { id: "mq_349", text: "Pain and foolishness lead to great bliss and complete knowledge, for Eternal Wisdom created nothing under the sun in vain.", author: "Kahlil Gibran" },
  { id: "mq_350", text: "The teacher who is indeed wise does not bid you to enter the house of his wisdom but rather leads you to the threshold of your mind.", author: "Kahlil Gibran" },
  { id: "mq_351", text: "To understand the heart and mind of a person, look not at what he has already achieved, but at what he aspires to do.", author: "Kahlil Gibran" },
  { id: "mq_352", text: "Wisdom ceases to be wisdom when it becomes too proud to weep, too grave to laugh, and too selfish to seek other than itself.", author: "Kahlil Gibran" },
  { id: "mq_353", text: "A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.", author: "Laozi" },
  { id: "mq_354", text: "By letting it go it all gets done. The world is won by those who let it go. But when you try and try. The world is beyond the winning.", author: "Laozi" },
  { id: "mq_355", text: "Give a man a fish and you feed him for a day. Teach him how to fish and you feed him for a lifetime.", author: "Laozi" },
  { id: "mq_356", text: "Great indeed is the sublimity of the Creative, to which all beings owe their beginning, and which permeates all heaven.", author: "Laozi" },
  { id: "mq_357", text: "I have just three things to teach: simplicity, patience, compassion. These three are your greatest treasures.", author: "Laozi" },
  { id: "mq_358", text: "If you would take, you must first give, this is the beginning of intelligence.", author: "Laozi" },
  { id: "mq_359", text: "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", author: "Laozi" },
  { id: "mq_360", text: "Knowing others is wisdom, knowing yourself is Enlightenment.", author: "Laozi" },
  { id: "mq_361", text: "The journey of a thousand miles begins with one step.", author: "Laozi" },
  { id: "mq_362", text: "A goal without a plan is just a wish.", author: "Larry Elder" },
  { id: "mq_363", text: "Life is a travelling to the edge of knowledge, then a leap taken.", author: "Laurence J. Peter" },
  { id: "mq_364", text: "There are two kinds of failures: those who thought and never did, and those who did and never thought.", author: "Laurence J. Peter" },
  { id: "mq_365", text: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy" },
];
