import type { ManifestQuote } from "./types";

export const QUOTES4: ManifestQuote[] = [
  { id: "mq_275", text: "Dünyada yalnızca sevinç olsaydı cesur ve sabırlı olmayı asla öğrenemezdik.", author: "Helen Keller" },
  { id: "mq_276", text: "Göz yalnızca zihnin anlamaya hazır olduğu şeyi görür.", author: "Henri Bergson" },
  { id: "mq_277", text: "Eylem insanı gibi düşün; düşünce insanı gibi hareket et.", author: "Henri Bergson" },
  { id: "mq_278", text: "Işığın varken çalış. Sana emanet edilen yetenekten sen sorumlusun.", author: "Henri-Frédéric Amiel" },
  { id: "mq_279", text: "Bugün dünyaya ait bilgelik sayılan pek çok şey, bir zamanlar bir bilgenin sevilmeyen aykırı düşüncesiydi.", author: "Henry David Thoreau" },
  { id: "mq_280", text: "Sevgiyle yapılan bilgisizlik ve beceriksizlik, sevgisiz bilgelik ve beceriden daha iyidir.", author: "Henry David Thoreau" },
  { id: "mq_281", text: "Umutsuzca davranmamak bilgeliğin özelliklerinden biridir.", author: "Henry David Thoreau" },
  { id: "mq_282", text: "Yapabileceğini düşünüyorsan yapabilirsin. Yapamayacağını düşünüyorsan da haklısın.", author: "Henry Ford" },
  { id: "mq_283", text: "Engeller, gözünü hedefinden ayırdığında gördüğün korkutucu şeylerdir.", author: "Henry Ford" },
  { id: "mq_284", text: "Sorun, iş kıyafeti giymiş bir fırsattan başka bir şey değildir.", author: "Henry J. Kaiser" },
  { id: "mq_285", text: "Başkalarının birileri hakkında söylediklerine körü körüne inanma. Herkesi ve her şeyi kendi gözlerinle değerlendir.", author: "Henry James" },
  { id: "mq_286", text: "Hayattan memnun ol; çünkü sana sevmek, çalışmak, oynamak ve yıldızlara bakmak için fırsat verir.", author: "Henry van Dyke Jr." },
  { id: "mq_287", text: "Bilgelik çoğu zaman bir sonraki adımda ne yapılacağını bilmektir.", author: "Herbert Hoover" },
  { id: "mq_288", text: "Bilgelik, ruhun bir hazırlığı; yaşamın her anında birlik düşüncelerini düşünebilme, hissedebilme ve soluyabilme yeteneğidir.", author: "Hermann Hesse" },
  { id: "mq_289", text: "Hata yapmaya devam edecek cesaretin varsa bilgeliğin ve zekân büyük bir hızla gelişir.", author: "Holly Near" },
  { id: "mq_290", text: "Zorluklara hazırlanmış bir kalp kötü zamanda umut eder, iyi zamanda ise talihin değişebileceğini bilir.", author: "Horace" },
  { id: "mq_291", text: "Başla, cesur ol ve bilgeleşmeye cesaret et.", author: "Horace" },
  { id: "mq_292", text: "Bütün bilgimiz duyularla başlar, anlayışla ilerler ve akılla sona erer. Akıldan daha yüksek bir şey yoktur.", author: "Immanuel Kant" },
  { id: "mq_293", text: "Bilim düzenlenmiş bilgidir. Bilgelik ise düzenlenmiş hayattır.", author: "Immanuel Kant" },
  { id: "mq_294", text: "Sevmeyi ancak severek öğrenebiliriz.", author: "Iris Murdoch" },
  { id: "mq_295", text: "Bugün hayatın en hüzünlü yanlarından biri, bilimin bilgiyi toplumun bilgelik kazanmasından daha hızlı toplamasıdır.", author: "Isaac Asimov" },
  { id: "mq_296", text: "Bilgelerin bilgeliği ve çağların deneyimi, sözler aracılığıyla korunabilir.", author: "Isaac D\\u0027Israeli" },
  { id: "mq_297", text: "Gerçek bilgelik, hiçbir şey bilmediğini bilmektir.", author: "Isocrates" },
  { id: "mq_298", text: "Gerçek bilgi, hiçbir şey bilmediğini bilmektir.", author: "Isocrates" },
  { id: "mq_299", text: "Gerçek bilgelik, hayatı, kendimizi ve çevremizdeki dünyayı ne kadar az anladığımızı fark ettiğimizde gelir.", author: "Isocrates" },
  { id: "mq_300", text: "Dünya yuvarlaktır; son gibi görünen yer aynı zamanda başlangıç olabilir.", author: "Ivy Baker Priest" },
  { id: "mq_301", text: "Hayatta sürekli ya ilerleriz ya gerileriz. Olduğumuz yerde kalmak diye bir şey yoktur.", author: "James Freeman Clarke" },
  { id: "mq_302", text: "Çok erken vazgeçip dünyayı kurtarabilecek son bir çabayı göstermemiş olma korkusundan daha kötü çok az şey vardır.", author: "Jane Addams" },
  { id: "mq_303", text: "Her insanla karşılaştığında kardeşlik için bir fırsat doğar.", author: "Jane Wyman" },
  { id: "mq_304", text: "Tam karanlıkta hepimiz aynıyız; bizi ayıran yalnızca bilgi ve bilgeliktir. Gözlerinin seni aldatmasına izin verme.", author: "Janet Jackson" },
  { id: "mq_305", text: "Bir lider ya da kriz anındaki eylem insanı çoğu zaman önce sezgisel olarak hareket eder, sonra davranışının nedenlerini düşünür.", author: "Jawaharlal Nehru" },
  { id: "mq_306", text: "Bilgeliğin en uç sınırına halk çoğu zaman delilik der.", author: "Jean Cocteau" },
  { id: "mq_307", text: "Hüzün zamanın kanatlarında uçar gider.", author: "Jean de La Fontaine" },
  { id: "mq_308", text: "İyilikten daha büyük hangi bilgelik olabilir?", author: "Jean-Jacques Rousseau" },
  { id: "mq_309", text: "Disiplin, hedeflerle başarı arasındaki köprüdür.", author: "Jim Rohn" },
  { id: "mq_310", text: "Bilgi konuşur, bilgelik dinler.", author: "Jimi Hendrix" },
  { id: "mq_311", text: "Düzeltmek çok şey yapar; teşvik etmek ise daha fazlasını.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_312", text: "Bana fikirlerini söyleyeceksen, neye inandığını söyle. Kendi şüphelerim bana zaten yetiyor.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_313", text: "Bazen kaderimiz kışın bir meyve ağacına benzer. O dalların yeniden yeşereceğini ve çiçek açacağını kim düşünür? Ama umut ederiz; biliriz.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_314", text: "Bilgelik yalnızca gerçekte bulunur.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_315", text: "Sabır ve azmin büyülü bir etkisi vardır; onların karşısında zorluklar ve engeller yok olur.", author: "John Adams" },
  { id: "mq_316", text: "Genç insanlar da zamanla bilgelik kazanabilir.", author: "John Bercow" },
  { id: "mq_317", text: "Bilgelik ne trenle, ne otomobille, ne uçakla gelir; telgrafla ya da telefonla da hızlandırılamaz.", author: "John Burroughs" },
  { id: "mq_318", text: "Benlik hazır yapılmış bir şey değildir; eylemlerimizde yaptığımız seçimlerle sürekli biçimlenir.", author: "John Dewey" },
  { id: "mq_319", text: "Hedefleri ve onlara ulaşmak için çabası olmadan insan yaşayamaz.", author: "John Dewey" },
  { id: "mq_320", text: "Bilgimiz arttıkça bilgisizliğimizin büyüklüğü daha açık hâle gelir.", author: "John F. Kennedy" },
  { id: "mq_321", text: "Çatıyı onarmanın zamanı güneşin parladığı zamandır.", author: "John F. Kennedy" },
  { id: "mq_322", text: "Büyük başarısızlıkları göze alanlar büyük başarılar elde edebilir.", author: "John F. Kennedy" },
  { id: "mq_323", text: "Beni başka bir şey için değil, olduğum kişi için sevdiğine inandığım için seni daha çok seviyorum.", author: "John Keats" },
  { id: "mq_324", text: "Gururlu insanı şöyle tanımlarım: ne boş bir gösterişe ne de bilgeliğe sahip olan; nefretle dolu kişi ne gerçekten gururlu ne de bilge olabilir.", author: "John Keats" },
  { id: "mq_325", text: "Keyifle geçirdiğin zaman boşa harcanmış değildir.", author: "John Lennon" },
  { id: "mq_326", text: "Keyifle geçirdiğin zaman boşa gitmiş değildir.", author: "John Lennon" },
  { id: "mq_327", text: "Benim bir hayalperest olduğumu söyleyebilirsin ama yalnız değilim; umarım bir gün sen de bize katılırsın ve dünya birlik içinde yaşar.", author: "John Lennon" },
  { id: "mq_328", text: "İnsanların eylemlerinin, düşüncelerinin en iyi yorumcusu olduğunu hep düşünmüşümdür.", author: "John Locke" },
  { id: "mq_329", text: "Bir gün boyunca endişelenmek, bir gün boyunca çalışmaktan daha yorucudur.", author: "John Lubbock" },
  { id: "mq_330", text: "Tek gerçek hata, bize hiçbir şey öğretmeyen hatadır.", author: "John Powell" },
  { id: "mq_331", text: "Eylemlerin başkalarına daha çok hayal kurmak, daha çok öğrenmek, daha çok yapmak ve daha iyi olmak için ilham veriyorsa sen bir lidersin.", author: "John Quincy Adams" },
  { id: "mq_332", text: "Kalite hiçbir zaman tesadüf değildir; her zaman akıllıca gösterilmiş çabanın sonucudur.", author: "John Ruskin" },
  { id: "mq_333", text: "Kendimizi az da olsa sevmeyi öğrenebilsek belki öfkemiz ve acımasızlığımız eriyip gider.", author: "John Steinbeck" },
  { id: "mq_334", text: "Gece zor görünen bir problemin, uyku üzerine çalıştıktan sonra sabah çözülmesi sık yaşanan bir deneyimdir.", author: "John Steinbeck" },
  { id: "mq_335", text: "Hayaller gerçekleşir. Bu ihtimal olmasaydı doğa bizi hayal kurmaya teşvik etmezdi.", author: "John Updike" },
  { id: "mq_336", text: "Meşguliyeti başarıyla karıştırma.", author: "John Wooden" },
  { id: "mq_337", text: "Dalgaları durduramazsın ama sörf yapmayı öğrenebilirsin.", author: "Jon Kabat-Zinn" },
  { id: "mq_338", text: "Sezgi, düşünen zihne bir sonraki bakması gereken yeri söyler.", author: "Jonas Salk" },
  { id: "mq_339", text: "Keşif, herkesin gördüğünü görüp kimsenin düşünmediğini düşünmektir.", author: "Jonathan Swift" },
  { id: "mq_340", text: "Öncelikle kendimizi ve kendi varlığımızı korumayı düşünmekten vazgeçtiğimizde bilincimizde gerçekten kahramanca bir dönüşüm yaşarız.", author: "Joseph Campbell" },
  { id: "mq_341", text: "Öğrenmeden hayal gücüne sahip olanın kanatları vardır ama ayakları yoktur.", author: "Joseph Joubert" },
  { id: "mq_342", text: "İlahi bilgeliğin yolunda yürüdükçe hayatında daha büyük ölçüde zafer ve başarı görmeye başlarsın.", author: "Joseph Prince" },
  { id: "mq_343", text: "Yalnızca bir şeye inanıyorum: insan iradesinin gücüne.", author: "Joseph Stalin" },
  { id: "mq_344", text: "Bilgelik insanı bağnaz yapmaz; fakat öğrenmiş olmak bazen yapabilir.", author: "Josh Billings" },
  { id: "mq_345", text: "Pek çok eğitimli ve zeki insan bilgelik ve sağduyudan yoksun olabilir.", author: "Joyce Meyer" },
  { id: "mq_346", text: "Kibir bilgeliğin önüne kolayca geçebilir; çoğu zaman sağduyunun da önüne geçer.", author: "Julian Casablancas" },
  { id: "mq_347", text: "Harekete geçen az bilgi, kullanılmadan duran çok bilgiden sonsuz ölçüde daha değerlidir.", author: "Kahlil Gibran" },
  { id: "mq_348", text: "Beni ağlamayan bilgelikten, gülmeyen felsefeden ve çocukların önünde eğilmeyen büyüklükten uzak tut.", author: "Kahlil Gibran" },
  { id: "mq_349", text: "Acı ve aptallık, büyük mutluluğa ve tam bilgiye götürebilir; çünkü sonsuz bilgelik güneşin altında hiçbir şeyi boşuna yaratmamıştır.", author: "Kahlil Gibran" },
  { id: "mq_350", text: "Gerçekten bilge öğretmen seni kendi bilgeliğinin evine çağırmaz; seni kendi zihninin eşiğine götürür.", author: "Kahlil Gibran" },
  { id: "mq_351", text: "Bir insanın kalbini ve zihnini anlamak için bugüne kadar ne başardığına değil, neyi başarmayı arzuladığına bak.", author: "Kahlil Gibran" },
  { id: "mq_352", text: "Bilgelik; ağlayamayacak kadar gururlu, gülemeyecek kadar ciddi ve kendinden başkasını aramayacak kadar bencil olduğunda bilgelik olmaktan çıkar.", author: "Kahlil Gibran" },
  { id: "mq_353", text: "En iyi lider, insanlar onun varlığını zar zor fark ettiğinde liderdir; iş bittiğinde ve hedefe ulaşıldığında insanlar 'Bunu biz yaptık' der.", author: "Laozi" },
  { id: "mq_354", text: "Bırakmayı bildiğinde işler yoluna girer. Dünya bazen bırakabilenlerin olur; sürekli zorladığında ise hedef senden uzaklaşabilir.", author: "Laozi" },
  { id: "mq_355", text: "Bir insana balık verirsen bir gün doyurursun; balık tutmayı öğretirsen ömür boyu doyurursun.", author: "Laozi" },
  { id: "mq_356", text: "Yaratıcılığın yüceliği büyüktür; bütün varlıklar başlangıçlarını ona borçludur ve o bütün göğü kaplar.", author: "Laozi" },
  { id: "mq_357", text: "Öğreteceğim yalnızca üç şey var: sadelik, sabır ve merhamet. Bu üçü en büyük hazinelerindir.", author: "Laozi" },
  { id: "mq_358", text: "Almak istiyorsan önce vermelisin; anlayışın başlangıcı budur.", author: "Laozi" },
  { id: "mq_359", text: "Sözlerde nezaket güven yaratır. Düşüncede nezaket derinlik, vermede nezaket sevgi yaratır.", author: "Laozi" },
  { id: "mq_360", text: "Başkalarını tanımak bilgelik, kendini tanımak aydınlanmadır.", author: "Laozi" },
  { id: "mq_361", text: "Binlerce kilometrelik yolculuk tek bir adımla başlar.", author: "Laozi" },
  { id: "mq_362", text: "Plansız hedef yalnızca bir dilektir.", author: "Larry Elder" },
  { id: "mq_363", text: "Hayat, bilginin sınırına kadar yapılan bir yolculuk ve sonra atılan bir sıçrayıştır.", author: "Laurence J. Peter" },
  { id: "mq_364", text: "İki tür başarısızlık vardır: düşünüp hiç yapmayanlar ve yapıp hiç düşünmeyenler.", author: "Laurence J. Peter" },
  { id: "mq_365", text: "Herkes dünyayı değiştirmeyi düşünür ama kimse kendini değiştirmeyi düşünmez.", author: "Leo Tolstoy" },
];
