import type { ManifestQuote } from "./types";

export const QUOTES1: ManifestQuote[] = [
  { id: "mq_001", text: "If I find 10,000 ways something won\u0027t work, I haven\u0027t failed. I am not discouraged, because every wrong attempt discarded is another step forward.", author: "Thomas Edison" },
  { id: "mq_002", text: "Nobody will believe in you unless you believe in yourself.", author: "Liberace" },
  { id: "mq_003", text: "Go for it now. The future is promised to no one.", author: "Wayne Dyer" },
  { id: "mq_004", text: "A creative man is motivated by the desire to achieve, not by the desire to beat others.", author: "Ayn Rand" },
  { id: "mq_005", text: "Never give up, for that is just the place and time that the tide will turn.", author: "Harriet Beecher Stowe" },
  { id: "mq_006", text: "I don\u0027t believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.", author: "Ken Venturi" },
  { id: "mq_007", text: "Don\u0027t wait. The time will never be just right.", author: "Napoleon Hill" },
  { id: "mq_008", text: "Effort only fully releases its reward after a person refuses to quit.", author: "Napoleon Hill" },
  { id: "mq_009", text: "In order to succeed, we must first believe that we can.", author: "Nikos Kazantzakis" },
  { id: "mq_010", text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
  { id: "mq_011", text: "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.", author: "Harriet Tubman" },
  { id: "mq_012", text: "If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success.", author: "John Locke" },
  { id: "mq_013", text: "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.", author: "Norman Vincent Peale" },
  { id: "mq_014", text: "Always bear in mind that your own resolution to succeed is more important than any one thing.", author: "Abraham Lincoln" },
  { id: "mq_015", text: "In the depth of winter, I finally learned that there was within me an invincible summer.", author: "Albert Camus" },
  { id: "mq_016", text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { id: "mq_017", text: "There is nothing impossible to him who will try.", author: "Alexander the Great" },
  { id: "mq_018", text: "The dream was always running ahead of me. To catch up, to live for a moment in unison with it, that was the miracle.", author: "Anaïs Nin" },
  { id: "mq_019", text: "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.", author: "Anatole France" },
  { id: "mq_020", text: "Set your goals high, and don\u0027t stop till you get there.", author: "Bo Jackson" },
  { id: "mq_021", text: "As you think, so shall you become.", author: "Bruce Lee" },
  { id: "mq_022", text: "In times of change, learners inherit the earth, while the learned find themselves beautifully equipped to deal with a world that no longer exists.", author: "Eric Hoffer" },
  { id: "mq_023", text: "Without hard work, nothing grows but weeds.", author: "Gordon Hinckley" },
  { id: "mq_024", text: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", author: "Helen Keller" },
  { id: "mq_025", text: "Whether you think you can or you think you can\u0027t, you are right.", author: "Henry Ford" },
  { id: "mq_026", text: "Believe deep down in your heart that you\u0027re destined to do great things.", author: "Joe Paterno" },
  { id: "mq_027", text: "Difficulties increase the nearer we get to the goal.", author: "Johann Wolfgang von Goethe" },
  { id: "mq_028", text: "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step.", author: "Laozi" },
  { id: "mq_029", text: "If you\u0027re changing the world, you\u0027re working on important things. You\u0027re excited to get up in the morning.", author: "Larry Page" },
  { id: "mq_030", text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
  { id: "mq_031", text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
  { id: "mq_032", text: "Change your life today. Don\u0027t gamble on the future, act now, without delay.", author: "Simone de Beauvoir" },
  { id: "mq_033", text: "Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious.", author: "Stephen Hawking" },
  { id: "mq_034", text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
  { id: "mq_035", text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { id: "mq_036", text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { id: "mq_037", text: "Difficulties are meant to rouse, not discourage. The human spirit is to grow strong by conflict.", author: "William Ellery Channing" },
  { id: "mq_038", text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { id: "mq_039", text: "Always bear in mind that your own resolution to succeed is more important than any other.", author: "Abraham Lincoln" },
  { id: "mq_040", text: "If A is success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your mouth shut.", author: "Albert Einstein" },
  { id: "mq_041", text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
  { id: "mq_042", text: "The art of progress is to preserve order amid change, and to preserve change amid order.", author: "Alfred North Whitehead" },
  { id: "mq_043", text: "To follow, without halt, one aim: There is the secret of success.", author: "Anna Pavlova" },
  { id: "mq_044", text: "Of course there is no formula for success except perhaps an unconditional acceptance of life and what it brings.", author: "Arthur Rubinstein" },
  { id: "mq_045", text: "Focusing your life solely on making a buck shows a poverty of ambition. It asks too little of yourself. And it will leave you unfulfilled.", author: "Barack Obama" },
  { id: "mq_046", text: "One secret of success in life is for a man to be ready for his opportunity when it comes.", author: "Benjamin Disraeli" },
  { id: "mq_047", text: "The secret of success is constancy to purpose.", author: "Benjamin Disraeli" },
  { id: "mq_048", text: "Through perseverance many people win success out of what seemed destined to be certain failure.", author: "Benjamin Disraeli" },
  { id: "mq_049", text: "Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it.", author: "Bruce Lee" },
  { id: "mq_050", text: "The person who makes a success of living is the one who see his goal steadily and aims for it unswervingly. That is dedication.", author: "Cecil B. DeMille" },
  { id: "mq_051", text: "One fails forward toward success.", author: "Charles F. Kettering" },
  { id: "mq_052", text: "There is only one success - to be able to spend your life in your own way.", author: "Christopher Morley" },
  { id: "mq_053", text: "There is only one success: to be able to spend your life in your own way.", author: "Christopher Morley" },
  { id: "mq_054", text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
  { id: "mq_055", text: "The person who lives life fully, glowing with life\u0027s energy, is the person who lives a successful life.", author: "Daisaku Ikeda" },
  { id: "mq_056", text: "A successful person is one who can lay a firm foundation with the bricks that others throw at him or her.", author: "David Brinkley" },
  { id: "mq_057", text: "Real success is finding your lifework in the work that you love.", author: "David McCullough" },
  { id: "mq_058", text: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Edward Everett Hale" },
  { id: "mq_059", text: "A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success.", author: "Elbert Hubbard" },
  { id: "mq_060", text: "Not every difficult and dangerous thing is suitable for training, but only that which is conducive to success in achieving the object of our effort.", author: "Epictetus" },
  { id: "mq_061", text: "It is on our failures that we base a new and different and better success.", author: "Havelock Ellis" },
  { id: "mq_062", text: "If one advances confidently in the direction of his dream, and endeavors to live the life which he had imagines, he will meet with a success unexpected in common hours.", author: "Henry David Thoreau" },
  { id: "mq_063", text: "Perseverance is a great element of success. If you only knock long enough and loud enough at the gate, you are sure to wake up somebody.", author: "Henry Wadsworth Longfellow" },
  { id: "mq_064", text: "I cannot give you the formula for success, but I can give you the formula for failure: which is: Try to please everybody.", author: "Herbert Bayard Swope" },
  { id: "mq_065", text: "If you focus on results, you will never change. If you focus on change, you will get results.", author: "Jack Dixon" },
  { id: "mq_066", text: "The most successful people are those who are good at plan B.", author: "James A. Yorke" },
  { id: "mq_067", text: "All the great performers I have worked with are fueled by a personal dream.", author: "John Eliot" },
  { id: "mq_068", text: "Until you value yourself, you won\u0027t value your time. Until you value your time, you won\u0027t do anything with it.", author: "M. Scott Peck" },
  { id: "mq_069", text: "It is not the possession of truth, but the success which attends the seeking after it, that enriches the seeker and brings happiness to him.", author: "Max Planck" },
  { id: "mq_070", text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { id: "mq_071", text: "Here is one quality that one must possess to win, and that is definiteness of purpose, the knowledge of what one wants, and a burning desire to possess it.", author: "Napoleon Hill" },
  { id: "mq_072", text: "Most great people have attained their greatest success just one step beyond their greatest failure.", author: "Napoleon Hill" },
  { id: "mq_073", text: "The ladder of success is never crowded at the top.", author: "Napoleon Hill" },
  { id: "mq_074", text: "You might well remember that nothing can bring you success but yourself.", author: "Napoleon Hill" },
  { id: "mq_075", text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { id: "mq_076", text: "The industrial landscape is already littered with remains of once successful companies that could not adapt their strategic vision to altered conditions of competition.", author: "Ralph Abernathy" },
  { id: "mq_077", text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson" },
  { id: "mq_078", text: "Self-trust is the first secret of success.", author: "Ralph Waldo Emerson" },
  { id: "mq_079", text: "Ask yourself the secret of your success. Listen to your answer and practice it.", author: "Richard Bach" },
  { id: "mq_080", text: "Many of life\u0027s failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison" },
  { id: "mq_081", text: "Results! Why, man, I have gotten a lot of results. I know several thousand things that won\u0027t work.", author: "Thomas Edison" },
  { id: "mq_082", text: "The first requisite for success is the ability to apply your physical and mental energies to one problem incessantly without growing weary.", author: "Thomas Edison" },
  { id: "mq_083", text: "Formula for success: under promise and over deliver.", author: "Tom Peters" },
  { id: "mq_084", text: "Successful people ask better questions, and as a result, they get better answers.", author: "Tony Robbins" },
  { id: "mq_085", text: "The path to success is to take massive, determined action.", author: "Tony Robbins" },
  { id: "mq_086", text: "Leaders aren\u0027t born they are made. And they are made just like anything else, through hard work. And that\u0027s the price we\u0027ll have to pay to achieve that goal, or any goal.", author: "Vince Lombardi" },
  { id: "mq_087", text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
  { id: "mq_088", text: "I can\u0027t imagine a person becoming a success who doesn\u0027t give this game of life everything he\u0027s got.", author: "Walter Cronkite" },
  { id: "mq_089", text: "Do more than dream: work.", author: "William Arthur Ward" },
  { id: "mq_090", text: "Six essential qualities that are the key to success: Sincerity, personal integrity, humility, courtesy, wisdom, charity.", author: "William C. Menninger" },
  { id: "mq_091", text: "Success consists of going from failure to failure without loss of enthusiasm.", author: "Winston Churchill" },
  { id: "mq_092", text: "Success is not final; failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
];
