import type { ManifestQuote } from "./types";

export const QUOTES2: ManifestQuote[] = [
  { id: "mq_093", text: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { id: "mq_094", text: "Wisdom and penetration are the fruit of experience, not the lessons of retirement and leisure. Great necessities call out great virtues.", author: "Abigail Adams" },
  { id: "mq_095", text: "Character is like a tree and reputation like a shadow. The shadow is what we think of it; the tree is the real thing.", author: "Abraham Lincoln" },
  { id: "mq_096", text: "Most people are about as happy as they make up their minds to be", author: "Abraham Lincoln" },
  { id: "mq_097", text: "The best thing about the future is that it only comes one day at a time.", author: "Abraham Lincoln" },
  { id: "mq_098", text: "When you have got an elephant by the hind legs and he is trying to run away, it\u0027s best to let him run.", author: "Abraham Lincoln" },
  { id: "mq_099", text: "You can fool all the people some of the time, and some of the people all the time, but you cannot fool all the people all the time.", author: "Abraham Lincoln" },
  { id: "mq_100", text: "It is good even for old men to learn wisdom.", author: "Aeschylus" },
  { id: "mq_101", text: "Wisdom comes alone through suffering.", author: "Aeschylus" },
  { id: "mq_102", text: "Appreciation is the highest form of prayer, for it acknowledges the presence of good wherever you shine the light of your thankful thoughts.", author: "Alan Cohen" },
  { id: "mq_103", text: "No valid plans for the future can be made by those who have no capacity for living now.", author: "Alan Watts" },
  { id: "mq_104", text: "A man should look for what is, and not for what he thinks should be.", author: "Albert Einstein" },
  { id: "mq_105", text: "Great ideas often receive violent opposition from mediocre minds.", author: "Albert Einstein" },
  { id: "mq_106", text: "I believe that a simple and unassuming manner of life is best for everyone, best both for the body and the mind.", author: "Albert Einstein" },
  { id: "mq_107", text: "I never think of the future. It comes soon enough.", author: "Albert Einstein" },
  { id: "mq_108", text: "Peace cannot be kept by force. It can only be achieved by understanding.", author: "Albert Einstein" },
  { id: "mq_109", text: "The attempt to combine wisdom and power has only rarely been successful and then only for a short while.", author: "Albert Einstein" },
  { id: "mq_110", text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
  { id: "mq_111", text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { id: "mq_112", text: "All human wisdom is summed up in two words; wait and hope.", author: "Alexandre Dumas" },
  { id: "mq_113", text: "There are two ways to slide easily through life: to believe everything or to doubt everything; both ways save us from thinking.", author: "Alfred Korzybski" },
  { id: "mq_114", text: "With age comes wisdom and a high sex drive. And the wisdom to enjoy it.", author: "Amber Valletta" },
  { id: "mq_115", text: "Love at first sight is easy to understand; it\u0027s when two people have been looking at each other for a lifetime that it becomes a miracle.", author: "Amy Bloom" },
  { id: "mq_116", text: "Dreams pass into the reality of action. From the actions stems the dream again; and this interdependence produces the highest form of living.", author: "Anaïs Nin" },
  { id: "mq_117", text: "Life shrinks or expands in proportion to one\u0027s courage.", author: "Anaïs Nin" },
  { id: "mq_118", text: "The possession of knowledge does not kill the sense of wonder and mystery. There is always more mystery.", author: "Anaïs Nin" },
  { id: "mq_119", text: "I prefer the folly of enthusiasm to the indifference of wisdom.", author: "Anatole France" },
  { id: "mq_120", text: "Irony is the gaiety of reflection and the joy of wisdom.", author: "Anatole France" },
  { id: "mq_121", text: "To accomplish great things, we must dream as well as act.", author: "Anatole France" },
  { id: "mq_122", text: "You learn to speak by speaking, to study by studying, to run by running, to work by working; in just the same way, you learn to love by loving.", author: "Anatole France" },
  { id: "mq_123", text: "They say that time changes things, but you actually have to change them yourself.", author: "Andy Warhol" },
  { id: "mq_124", text: "If we had no winter, the spring would not be so pleasant; if we did not sometimes taste of adversity, prosperity would not be so welcome.", author: "Anne Bradstreet" },
  { id: "mq_125", text: "In wisdom gathered over time I have found that every experience is a form of exploration.", author: "Ansel Adams" },
  { id: "mq_126", text: "Knowledge is of no value unless you put it into practice.", author: "Anton Chekhov" },
  { id: "mq_127", text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { id: "mq_128", text: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { id: "mq_129", text: "The virtue of justice consists in moderation, as regulated by wisdom.", author: "Aristotle" },
  { id: "mq_130", text: "In action a great heart is the chief qualification. In work, a great head.", author: "Arthur Schopenhauer" },
  { id: "mq_131", text: "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone.", author: "Audrey Hepburn" },
  { id: "mq_132", text: "Patience is the companion of wisdom.", author: "Augustine of Hippo" },
  { id: "mq_133", text: "Without courage, wisdom bears no fruit.", author: "Baltasar Gracián" },
  { id: "mq_134", text: "Change will not come if we wait for some other person or some other time. We are the ones we\u0027ve been waiting for. We are the change that we seek.", author: "Barack Obama" },
  { id: "mq_135", text: "If you\u0027re walking down the right path and you\u0027re willing to keep walking, eventually you\u0027ll make progress.", author: "Barack Obama" },
  { id: "mq_136", text: "No party has a monopoly on wisdom. No democracy works without compromise.", author: "Barack Obama" },
  { id: "mq_137", text: "We need to find the courage to say NO to the things and people that are not serving us if we want to rediscover ourselves and live our lives with authenticity.", author: "Barbara De Angelis" },
  { id: "mq_138", text: "Action may not always bring happiness; but there is no happiness without action.", author: "Benjamin Disraeli" },
  { id: "mq_139", text: "Dost thou love life? Then do not squander time, for that is the stuff life is made of.", author: "Benjamin Franklin" },
  { id: "mq_140", text: "Experience keeps a dear school, but fools will learn in no other.", author: "Benjamin Franklin" },
  { id: "mq_141", text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { id: "mq_142", text: "The doors of wisdom are never shut.", author: "Benjamin Franklin" },
  { id: "mq_143", text: "The doorstep to the temple of wisdom is a knowledge of our own ignorance.", author: "Benjamin Franklin" },
  { id: "mq_144", text: "Without freedom of thought, there can be no such thing as wisdom - and no such thing as public liberty without freedom of speech.", author: "Benjamin Franklin" },
  { id: "mq_145", text: "Trust yourself. You know more than you think you do.", author: "Benjamin Spock" },
  { id: "mq_146", text: "Beware of false knowledge; it is more dangerous than ignorance.", author: "Bernard Shaw" },
  { id: "mq_147", text: "We are made wise not by the recollection of our past, but by the responsibility for our future.", author: "Bernard Shaw" },
  { id: "mq_148", text: "To conquer fear is the beginning of wisdom.", author: "Bertrand Russell" },
  { id: "mq_149", text: "Imagination allows us to escape the predictable. It enables us to reply to the common wisdom that we cannot soar by saying, \u0027Just watch!\u0027", author: "Bill Bradley" },
  { id: "mq_150", text: "We must learn our limits. We are all something, but none of us are everything.", author: "Blaise Pascal" },
  { id: "mq_151", text: "Not engaging in ignorance is wisdom.", author: "Bodhidharma" },
  { id: "mq_152", text: "Knowledge is knowing that a tomato is a fruit. Wisdom is knowing not to put it in a fruit salad.", author: "Brian O\u0027Driscoll" },
  { id: "mq_153", text: "Goals are the fuel in the furnace of achievement.", author: "Brian Tracy" },
  { id: "mq_154", text: "There is never enough time to do everything, but there is always enough time to do the most important thing.", author: "Brian Tracy" },
  { id: "mq_155", text: "You can only grow if you\u0027re willing to feel awkward and uncomfortable when you try something new.", author: "Brian Tracy" },
  { id: "mq_156", text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "Bruce Lee" },
  { id: "mq_157", text: "If you love life, don\u0027t waste time, for time is what life is made up of.", author: "Bruce Lee" },
  { id: "mq_158", text: "If you spend too much time thinking about a thing, you\u0027ll never get it done.", author: "Bruce Lee" },
  { id: "mq_159", text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee" },
  { id: "mq_160", text: "The less effort, the faster and more powerful you will be.", author: "Bruce Lee" },
  { id: "mq_161", text: "To know oneself is to study oneself in action with another person.", author: "Bruce Lee" },
  { id: "mq_162", text: "Knowledge rests not upon truth alone, but upon error also.", author: "Carl Jung" },
  { id: "mq_163", text: "Who looks outside, dreams, who looks inside, awakes.", author: "Carl Jung" },
  { id: "mq_164", text: "Without this playing with fantasy no creative work has ever yet come to birth. The debt we owe to the play of the imagination is incalculable.", author: "Carl Jung" },
  { id: "mq_165", text: "Your vision will become clear only when you can look into your own heart. Who looks outside, dreams, who looks inside, awakes.", author: "Carl Jung" },
  { id: "mq_166", text: "Your vision will become clear only when you look into your heart. Who looks outside, dreams. Who looks inside, awakens.", author: "Carl Jung" },
  { id: "mq_167", text: "Nothing happens unless first we dream.", author: "Carl Sandburg" },
  { id: "mq_168", text: "The trick is in what one emphasizes. We either make ourselves miserable, or we make ourselves happy. The amount of work is the same.", author: "Carlos Castaneda" },
  { id: "mq_169", text: "There is a wisdom of the head, and a wisdom of the heart.", author: "Charles Dickens" },
  { id: "mq_170", text: "The greatest pleasure I know is to do a good action by stealth, and to have it found out by accident.", author: "Charles Lamb" },
  { id: "mq_171", text: "Life a culmination of the past, an awareness of the present, an indication of the future beyond knowledge, the quality that gives a touch of divinity to matter.", author: "Charles Lindbergh" },
  { id: "mq_172", text: "Impossibilities are merely things which we have not yet learned.", author: "Charles W. Chesnutt" },
  { id: "mq_173", text: "A ruffled mind makes a restless pillow.", author: "Charlotte Brontë" },
  { id: "mq_174", text: "Let us revere, let us worship, but erect and open-eyed, the highest, not the lowest; the future, not the past!", author: "Charlotte Perkins Gilman" },
  { id: "mq_175", text: "Never accept ultimatums, conventional wisdom, or absolutes.", author: "Christopher Reeve" },
  { id: "mq_176", text: "A lot of times people look at the negative side of what they feel they can\u0027t do. I always look on the positive side of what I can do.", author: "Chuck Norris" },
  { id: "mq_177", text: "The function of wisdom is to discriminate between good and evil.", author: "Cicero" },
  { id: "mq_178", text: "If you are going to achieve excellence in big things, you develop the habit in little matters. Excellence is not an exception; it is a prevailing attitude.", author: "Colin Powell" },
  { id: "mq_179", text: "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", author: "Confucius" },
  { id: "mq_180", text: "Learning without reflection is a waste, reflection without learning is dangerous.", author: "Confucius" },
  { id: "mq_181", text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { id: "mq_182", text: "Reviewing what you have learned and learning anew, you are fit to be a teacher.", author: "Confucius" },
  { id: "mq_183", text: "Study the past, if you would divine the future.", author: "Confucius" },
];
