import type { ManifestQuote } from "./types";

export const QUOTES3: ManifestQuote[] = [
  { id: "mq_184", text: "The superior man acts before he speaks, and afterwards speaks according to his action.", author: "Confucius" },
  { id: "mq_185", text: "The superior man is modest in his speech but exceeds in his actions.", author: "Confucius" },
  { id: "mq_186", text: "They must often change, who would be constant in happiness or wisdom.", author: "Confucius" },
  { id: "mq_187", text: "To give oneself earnestly to the duties due to men, and, while respecting spiritual beings, to keep aloof from them, may be called wisdom.", author: "Confucius" },
  { id: "mq_188", text: "To study and not think is a waste. To think and not study is dangerous.", author: "Confucius" },
  { id: "mq_189", text: "When it is obvious that the goals cannot be reached, don\u0027t adjust the goals, adjust the action steps.", author: "Confucius" },
  { id: "mq_190", text: "When you see a good person, think of becoming like him. When you see someone not so good, reflect on your own weak points.", author: "Confucius" },
  { id: "mq_191", text: "When you see a man of worth, think of how you may emulate him. When you see one who is unworthy, examine yourself.", author: "Confucius" },
  { id: "mq_192", text: "Wisdom, compassion, and courage are the three universally recognized moral qualities of men.", author: "Confucius" },
  { id: "mq_193", text: "To want to be what one can be is purpose in life.", author: "Cynthia Ozick" },
  { id: "mq_194", text: "True happiness means forging a strong spirit that is undefeated, no matter how trying our circumstances.", author: "Daisaku Ikeda" },
  { id: "mq_195", text: "By going beyond your own problems and taking care of others, you gain inner strength, self-confidence, courage, and a greater sense of calm.", author: "Dalai Lama" },
  { id: "mq_196", text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
  { id: "mq_197", text: "I believe that we are fundamentally the same and have the same basic potential.", author: "Dalai Lama" },
  { id: "mq_198", text: "I find hope in the darkest of days, and focus in the brightest. I do not judge the universe.", author: "Dalai Lama" },
  { id: "mq_199", text: "It is difficult to achieve a spirit of genuine cooperation as long as people remain indifferent to the feelings and happiness of others.", author: "Dalai Lama" },
  { id: "mq_200", text: "Remember that sometimes not getting what you want is a wonderful stroke of luck.", author: "Dalai Lama" },
  { id: "mq_201", text: "See the positive side, the potential, and make an effort.", author: "Dalai Lama" },
  { id: "mq_202", text: "The key to transforming our hearts and minds is to have an understanding of how our thoughts and emotions work.", author: "Dalai Lama" },
  { id: "mq_203", text: "The most important thing is transforming our minds, for a new way of thinking, a new outlook: we should strive to develop a new inner world.", author: "Dalai Lama" },
  { id: "mq_204", text: "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.", author: "Dale Carnegie" },
  { id: "mq_205", text: "When fate hands us a lemon, let\u0027s try to make lemonade.", author: "Dale Carnegie" },
  { id: "mq_206", text: "Some of the best lessons we ever learn are learned from past mistakes. The error of the past is the wisdom and success of the future.", author: "Dale Turner" },
  { id: "mq_207", text: "The greatest obstacle to discovery is not ignorance - it is the illusion of knowledge.", author: "Daniel J. Boorstin" },
  { id: "mq_208", text: "Wisdom begins at the end.", author: "Daniel Webster" },
  { id: "mq_209", text: "It\u0027s important to know that words don\u0027t move mountains. Work, exacting work moves mountains.", author: "Danilo Dolci" },
  { id: "mq_210", text: "No day in which you learn something is a complete loss.", author: "David Eddings" },
  { id: "mq_211", text: "Small opportunities are often the beginning of great enterprises.", author: "Demosthenes" },
  { id: "mq_212", text: "Fear grows in darkness; if you think there\u0027s a bogeyman around, turn on the light.", author: "Dorothy Thompson" },
  { id: "mq_213", text: "Only when we are no longer afraid do we begin to live.", author: "Dorothy Thompson" },
  { id: "mq_214", text: "Wisdom is the reward you get for a lifetime of listening when you\u0027d have preferred to talk.", author: "Doug Larson" },
  { id: "mq_215", text: "Human beings, who are almost unique in having the ability to learn from the experience of others, are also remarkable for their apparent disinclination to do so.", author: "Douglas Adams" },
  { id: "mq_216", text: "You know you\u0027re in love when you can\u0027t fall asleep because reality is finally better than your dreams.", author: "Dr. Seuss" },
  { id: "mq_217", text: "It takes courage to grow up and become who you really are.", author: "E. E. Cummings" },
  { id: "mq_218", text: "The greater part of human pain is unnecessary. It is self-created as long as the unobserved mind runs your life.", author: "Eckhart Tolle" },
  { id: "mq_219", text: "You do not become good by trying to be good, but by finding the goodness that is already within you.", author: "Eckhart Tolle" },
  { id: "mq_220", text: "All that we see or seem is but a dream within a dream.", author: "Edgar Allan Poe" },
  { id: "mq_221", text: "Those who dream by day are cognizant of many things which escape those who dream only by night.", author: "Edgar Allan Poe" },
  { id: "mq_222", text: "If only wed stop trying to be happy wed have a pretty good time.", author: "Edith Wharton" },
  { id: "mq_223", text: "Life is the only real counselor; wisdom unfiltered through personal experience does not become a part of the moral tissue.", author: "Edith Wharton" },
  { id: "mq_224", text: "But what is liberty without wisdom, and without virtue? It is the greatest of all possible evils; for it is folly, vice, and madness, without tuition or restraint.", author: "Edmund Burke" },
  { id: "mq_225", text: "On every thorn, delightful wisdom grows, in every rill a sweet instruction flows.", author: "Edward Young" },
  { id: "mq_226", text: "Through meditation and by giving full attention to one thing at a time, we can learn to direct attention where we choose.", author: "Eknath Easwaran" },
  { id: "mq_227", text: "A failure is a man who has blundered but is not capable of cashing in on the experience.", author: "Elbert Hubbard" },
  { id: "mq_228", text: "Every man is a damn fool for at least five minutes every day; wisdom consists in not exceeding the limit.", author: "Elbert Hubbard" },
  { id: "mq_229", text: "There is no failure except in no longer trying.", author: "Elbert Hubbard" },
  { id: "mq_230", text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { id: "mq_231", text: "I think somehow, we learn who we really are and then live with that decision.", author: "Eleanor Roosevelt" },
  { id: "mq_232", text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { id: "mq_233", text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
  { id: "mq_234", text: "I believe that we are solely responsible for our choices, and we have to accept the consequences of every deed, word, and thought throughout our lifetime.", author: "Elisabeth Kübler-Ross" },
  { id: "mq_235", text: "Whoso loves, believes the impossible.", author: "Elizabeth Browning" },
  { id: "mq_236", text: "The truest greatness lies in being kind, the truest wisdom in a happy mind.", author: "Ella Wheeler Wilcox" },
  { id: "mq_237", text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus" },
  { id: "mq_238", text: "Practice yourself, for heaven\u0027s sake in little things, and then proceed to greater.", author: "Epictetus" },
  { id: "mq_239", text: "When you are offended at any man\u0027s fault, turn to yourself and study your own failings. Then you will forget your anger.", author: "Epictetus" },
  { id: "mq_240", text: "Never mistake motion for action.", author: "Ernest Hemingway" },
  { id: "mq_241", text: "Sometimes the most important thing in a whole day is the rest we take between two deep breaths.", author: "Etty Hillesum" },
  { id: "mq_242", text: "Along with success comes a reputation for wisdom.", author: "Euripides" },
  { id: "mq_243", text: "Cleverness is not wisdom.", author: "Euripides" },
  { id: "mq_244", text: "I am a man of fixed and unbending principles, the first of which is to be flexible at all times.", author: "Everett Dirksen" },
  { id: "mq_245", text: "A monarchy conducted with infinite wisdom and infinite benevolence is the most perfect of all possible governments.", author: "Ezra Stiles" },
  { id: "mq_246", text: "A prudent question is one half of wisdom.", author: "Francis Bacon" },
  { id: "mq_247", text: "Silence is the sleep that nourishes wisdom.", author: "Francis Bacon" },
  { id: "mq_248", text: "Pure, holy simplicity confounds all the wisdom of this world and the wisdom of the flesh.", author: "Francis of Assisi" },
  { id: "mq_249", text: "Where there is charity and wisdom, there is neither fear nor ignorance.", author: "Francis of Assisi" },
  { id: "mq_250", text: "We all grow up. Hopefully, we get wiser. Age brings wisdom, and fatherhood changes one\u0027s life completely.", author: "Frank Abagnale" },
  { id: "mq_251", text: "The beginning of knowledge is the discovery of something we do not understand.", author: "Frank Herbert" },
  { id: "mq_252", text: "Respect should be earned by actions, and not acquired by years.", author: "Frank Lloyd Wright" },
  { id: "mq_253", text: "The thing always happens that you really believe in; and the belief in a thing makes it happen.", author: "Frank Lloyd Wright" },
  { id: "mq_254", text: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin D. Roosevelt" },
  { id: "mq_255", text: "It is common sense to take a method and try it. If it fails, admit it frankly and try another. But above all, try something.", author: "Franklin D. Roosevelt" },
  { id: "mq_256", text: "Genius unrefined resembles a flash of lightning, but wisdom is like the sun.", author: "Franz Grillparzer" },
  { id: "mq_257", text: "If there is no struggle, there is no progress.", author: "Frederick Douglass" },
  { id: "mq_258", text: "Does wisdom perhaps appear on the earth as a raven which is inspired by the smell of carrion?", author: "Friedrich Nietzsche" },
  { id: "mq_259", text: "The man of knowledge must be able not only to love his enemies but also to hate his friends.", author: "Friedrich Nietzsche" },
  { id: "mq_260", text: "There is more wisdom in your body than in your deepest philosophy.", author: "Friedrich Nietzsche" },
  { id: "mq_261", text: "I do not believe in a fate that falls on men however they act; but I do believe in a fate that falls on man unless they act.", author: "G. K. Chesterton" },
  { id: "mq_262", text: "I do not believe in a fate that falls on men however they act; but I do believe in a fate that falls on them unless they act.", author: "G. K. Chesterton" },
  { id: "mq_263", text: "Where is the Life we have lost in living? Where is the wisdom we have lost in knowledge? Where is the knowledge we have lost in information?", author: "George Eliot" },
  { id: "mq_264", text: "Myths which are believed in tend to become true.", author: "George Orwell" },
  { id: "mq_265", text: "Those who cannot learn from history are doomed to repeat it.", author: "George Santayana" },
  { id: "mq_266", text: "Without leaps of imagination, or dreaming, we lose the excitement of possibilities. Dreaming, after all, is a form of planning.", author: "Gloria Steinem" },
  { id: "mq_267", text: "Our kindness may be the most persuasive argument for that which we believe.", author: "Gordon Hinckley" },
  { id: "mq_268", text: "Our lives are the only meaningful expression of what we believe and in Whom we believe. And the only real wealth, for any of us, lies in our faith.", author: "Gordon Hinckley" },
  { id: "mq_269", text: "Our character is what we do when we think no one is looking.", author: "H. Jackson Brown Jr." },
  { id: "mq_270", text: "Think big thoughts but relish small pleasures.", author: "H. Jackson Brown Jr." },
  { id: "mq_271", text: "It is not so important to know everything as to appreciate what we learn.", author: "Hannah More" },
  { id: "mq_272", text: "Obstacles are those things you see when you take your eyes off the goal.", author: "Hannah More" },
  { id: "mq_273", text: "The poor man is not he who is without a cent, but he who is without a dream.", author: "Harry Kemp" },
  { id: "mq_274", text: "Face your deficiencies and acknowledge them; but do not let them master you. Let them teach you patience, sweetness, insight.", author: "Helen Keller" },
];
