import {
  makeTopics,
} from "../builders";

export const TYT_MATEMATIK_TOPICS =
  makeTopics([
    ["tm_temel_kavramlar", "Temel Kavramlar"],
    ["tm_sayi_basamaklari", "Sayı Basamakları"],
    ["tm_bolme", "Bölme ve Bölünebilme"],
    ["tm_ebob_ekok", "EBOB – EKOK"],
    ["tm_rasyonel", "Rasyonel Sayılar"],
    ["tm_esitsizlik", "Basit Eşitsizlikler"],
    ["tm_mutlak", "Mutlak Değer"],
    ["tm_uslu", "Üslü Sayılar"],
    ["tm_koklu", "Köklü Sayılar"],
    ["tm_carpanlar", "Çarpanlara Ayırma"],
    ["tm_oran", "Oran – Orantı"],
    ["tm_denklem", "Denklem Çözme"],
    ["tm_sayi_problem", "Sayı Problemleri"],
    ["tm_kesir_problem", "Kesir Problemleri"],
    ["tm_yas_problem", "Yaş Problemleri"],
    ["tm_hareket_problem", "Hareket Problemleri"],
    ["tm_isci_havuz", "İşçi – Havuz Problemleri"],
    ["tm_yuzde_kar", "Yüzde, Kâr – Zarar Problemleri"],
    ["tm_karisim", "Karışım Problemleri"],
    ["tm_kumeler", "Kümeler"],
    ["tm_fonksiyon", "Fonksiyonlar"],
    ["tm_mantik", "Mantık"],
    ["tm_permutasyon", "Permütasyon"],
    ["tm_kombinasyon", "Kombinasyon"],
    ["tm_olasilik", "Olasılık"],
    ["tm_veri", "Veri ve İstatistik"],

    ["tg_kavramlar", "Geometri: Geometrik Kavramlar"],
    ["tg_dogruda_acilar", "Geometri: Doğruda Açılar"],
    ["tg_ucgende_acilar", "Geometri: Üçgende Açılar"],
    ["tg_ucgenler", "Geometri: Üçgenler"],
    ["tg_ucgende_alan", "Geometri: Üçgende Alan"],
    ["tg_benzerlik", "Geometri: Üçgende Benzerlik"],
    ["tg_aciortay", "Geometri: Açıortay ve Kenarortay"],
    ["tg_dortgenler", "Geometri: Dörtgenler"],
    ["tg_cokgenler", "Geometri: Çokgenler"],
    ["tg_cember", "Geometri: Çember ve Daire"],
    ["tg_kati_cisimler", "Geometri: Katı Cisimler"],
    ["tg_analitik", "Geometri: Analitik Geometri"],
  ]);