import {
  makeTopics,
} from "../builders";

export const TYT_SOSYAL_TOPICS =
  makeTopics([
    ["ts_tar_tarih_zaman", "Tarih: Tarih ve Zaman"],
    ["ts_tar_ilk_donem", "Tarih: İnsanlığın İlk Dönemleri"],
    ["ts_tar_orta_cag", "Tarih: Orta Çağ’da Dünya"],
    ["ts_tar_turk_dunyasi", "Tarih: İlk ve Orta Çağlarda Türk Dünyası"],
    ["ts_tar_islam", "Tarih: İslam Medeniyetinin Doğuşu"],
    ["ts_tar_turk_islam", "Tarih: Türklerin İslamiyet’i Kabulü ve İlk Türk İslam Devletleri"],
    ["ts_tar_selcuklu", "Tarih: Selçuklu Türkiyesi"],
    ["ts_tar_osmanli_beylik", "Tarih: Beylikten Devlete Osmanlı Siyaseti"],
    ["ts_tar_osmanli_guc", "Tarih: Dünya Gücü Osmanlı"],
    ["ts_tar_degisen_dunya", "Tarih: Değişen Dünya Dengeleri Karşısında Osmanlı"],
    ["ts_tar_milli", "Tarih: Millî Mücadele"],
    ["ts_tar_inkilap", "Tarih: Atatürk İlke ve İnkılapları"],
    ["ts_tar_dis_politika", "Tarih: Atatürk Dönemi Türk Dış Politikası"],

    ["ts_cog_doga_insan", "Coğrafya: Doğa ve İnsan"],
    ["ts_cog_dunya", "Coğrafya: Dünya’nın Şekli ve Hareketleri"],
    ["ts_cog_konum", "Coğrafya: Coğrafi Konum"],
    ["ts_cog_harita", "Coğrafya: Harita Bilgisi"],
    ["ts_cog_atmosfer", "Coğrafya: Atmosfer ve Sıcaklık"],
    ["ts_cog_basinc", "Coğrafya: Basınç ve Rüzgârlar"],
    ["ts_cog_nem", "Coğrafya: Nem, Yağış ve Buharlaşma"],
    ["ts_cog_iklim", "Coğrafya: İklim Bilgisi"],
    ["ts_cog_kuvvet", "Coğrafya: İç ve Dış Kuvvetler"],
    ["ts_cog_su_toprak", "Coğrafya: Su, Toprak ve Bitkiler"],
    ["ts_cog_nufus", "Coğrafya: Nüfus ve Yerleşme"],
    ["ts_cog_goc", "Coğrafya: Göç"],
    ["ts_cog_ekonomi", "Coğrafya: Ekonomik Faaliyetler"],
    ["ts_cog_bolgeler", "Coğrafya: Bölgeler"],
    ["ts_cog_afet", "Coğrafya: Doğal Afetler"],

    ["ts_fel_tanima", "Felsefe: Felsefeyi Tanıma"],
    ["ts_fel_dusunme", "Felsefe: Felsefe ile Düşünme"],
    ["ts_fel_varlik", "Felsefe: Varlık Felsefesi"],
    ["ts_fel_bilgi", "Felsefe: Bilgi Felsefesi"],
    ["ts_fel_bilim", "Felsefe: Bilim Felsefesi"],
    ["ts_fel_ahlak", "Felsefe: Ahlak Felsefesi"],
    ["ts_fel_din", "Felsefe: Din Felsefesi"],
    ["ts_fel_siyaset", "Felsefe: Siyaset Felsefesi"],
    ["ts_fel_sanat", "Felsefe: Sanat Felsefesi"],
    ["ts_fel_okuma", "Felsefe: Felsefi Okuma ve Yorumlama"],

    ["ts_din_bilgi", "Din: Bilgi ve İnanç"],
    ["ts_din_islam", "Din: Din ve İslam"],
    ["ts_din_ibadet", "Din: İslam ve İbadet"],
    ["ts_din_genclik", "Din: Gençlik ve Değerler"],
    ["ts_din_gonul", "Din: Gönül Coğrafyamız"],
    ["ts_din_allah_insan", "Din: Allah–İnsan İlişkisi"],
    ["ts_din_muhammed", "Din: Hz. Muhammed ve Gençlik"],
    ["ts_din_hayat", "Din: Din ve Hayat"],
    ["ts_din_ahlak", "Din: Ahlaki Tutum ve Davranışlar"],
    ["ts_din_yorumlar", "Din: İtikadi ve Siyasi Yorumlar"],
    ["ts_din_medeniyet", "Din: Din, Kültür ve Medeniyet"],
  ]);